// Code generated by PuppyDSL. DO NOT EDIT.

package artifact_modules

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var getCatalogFunction = native.Function{
	ID:        "drmcp_runtime.artifact_modules._get_catalog",
	Signature: "() -> ArtifactModuleCatalog",
}

// GetCatalog Returns the frozen artifact module catalog activated during runtime bootstrap.
func GetCatalog(call native.Call) (types.ArtifactModuleCatalog, error) {
	value, err := call.Invoke(getCatalogFunction, nil)
	if err != nil {
		var zero types.ArtifactModuleCatalog
		return zero, err
	}
	return native.Output[types.ArtifactModuleCatalog](getCatalogFunction, value)
}
