// Code generated by PuppyDSL. DO NOT EDIT.

package config

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var loadRepositoryConfigurationFunction = native.Function{
	ID:        "drmcp_runtime.config._load_repository_configuration",
	Signature: "(repository_root: RepositoryRoot) -> RepositoryConfiguration",
}

// LoadRepositoryConfiguration Loads the repository configuration file from the supplied repository root.
func LoadRepositoryConfiguration(call native.Call, repositoryRoot types.RepositoryRoot) (types.RepositoryConfiguration, error) {
	value, err := call.Invoke(loadRepositoryConfigurationFunction, []any{repositoryRoot})
	if err != nil {
		var zero types.RepositoryConfiguration
		return zero, err
	}
	return native.Output[types.RepositoryConfiguration](loadRepositoryConfigurationFunction, value)
}

var requireCurrentSourceRootsFunction = native.Function{
	ID:        "drmcp_runtime.config._require_current_source_roots",
	Signature: "( repository_root: RepositoryRoot, configuration: RepositoryConfiguration ) -> void",
}

// RequireCurrentSourceRoots Confirms that every configured current source records root exists as a directory under the supplied repository root.
func RequireCurrentSourceRoots(call native.Call, repositoryRoot types.RepositoryRoot, configuration types.RepositoryConfiguration) error {
	_, err := call.Invoke(requireCurrentSourceRootsFunction, []any{repositoryRoot, configuration})
	return err
}

var validateAndGetRepositoryConfigurationFunction = native.Function{
	ID:        "drmcp_runtime.config._validate_and_get_repository_configuration",
	Signature: "(repository_root: RepositoryRoot) -> RepositoryConfiguration",
}

// ValidateAndGetRepositoryConfiguration Loads the repository configuration and confirms that every configured current source root exists as a directory.
func ValidateAndGetRepositoryConfiguration(call native.Call, repositoryRoot types.RepositoryRoot) (types.RepositoryConfiguration, error) {
	value, err := call.Invoke(validateAndGetRepositoryConfigurationFunction, []any{repositoryRoot})
	if err != nil {
		var zero types.RepositoryConfiguration
		return zero, err
	}
	return native.Output[types.RepositoryConfiguration](validateAndGetRepositoryConfigurationFunction, value)
}
