// Code generated by PuppyDSL. DO NOT EDIT.

package mcp

import (
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var serveFunction = native.Function{
	ID:        "drmcp_runtime.mcp.serve",
	Signature: "() -> void",
}

// Serve Registers the configured public MCP tools and serves requests over the process transport.
func Serve(call native.Call) error {
	_, err := call.Invoke(serveFunction, nil)
	return err
}

// ServeImplementation is the concrete Go signature accepted by BindServe.
type ServeImplementation func(call native.Call) error

// BindServe binds a Go implementation to PuppyDSL function drmcp_runtime.mcp.serve.
func BindServe(implementation ServeImplementation) native.Binding {
	if implementation == nil {
		return native.NewBinding(serveFunction, "mcp.serve", nil)
	}
	return native.NewBinding(
		serveFunction,
		"mcp.serve",
		func(call native.Call, arguments []any) (any, error) {
			if len(arguments) != 0 {
				return nil, native.ArgumentCountError(serveFunction, 0, len(arguments))
			}
			if err := implementation(call); err != nil {
				return nil, err
			}
			return nil, nil
		},
	)
}
