// Code generated by PuppyDSL. DO NOT EDIT.

package current_record

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var buildArtifactRecordIndexEntryFunction = native.Function{
	ID:        "artifact.base.current_record._build_artifact_record_index_entry",
	Signature: "( app_namespace: AppNamespace, artifact_kind: ArtifactKind, discovery: ArtifactSourceRootDiscovery, records: dict<CanonicalRecordReference, CurrentRecord> ) -> CurrentArtifactRecordIndexEntry",
}

// BuildArtifactRecordIndexEntry Routes one available structure-specific physical discovery to the corresponding current-record index builder and preserves its artifact-kind key.
func BuildArtifactRecordIndexEntry(call native.Call, appNamespace types.AppNamespace, artifactKind types.ArtifactKind, discovery types.ArtifactSourceRootDiscovery, records map[types.CanonicalRecordReference]types.CurrentRecord) (types.CurrentArtifactRecordIndexEntry, error) {
	value, err := call.Invoke(buildArtifactRecordIndexEntryFunction, []any{appNamespace, artifactKind, discovery, records})
	if err != nil {
		var zero types.CurrentArtifactRecordIndexEntry
		return zero, err
	}
	return native.Output[types.CurrentArtifactRecordIndexEntry](buildArtifactRecordIndexEntryFunction, value)
}

var buildCurrentAppIndexesFunction = native.Function{
	ID:        "artifact.base.current_record._build_current_app_indexes",
	Signature: "( inventory: RepositoryDiscoveryInventory, records: dict<CanonicalRecordReference, CurrentRecord> ) -> dict<AppNamespace, CurrentAppRecordIndex>",
}

// BuildCurrentAppIndexes Builds every configured app's available structure-specific indexes from shared physical discovery and uniquely addressable records.
func BuildCurrentAppIndexes(call native.Call, inventory types.RepositoryDiscoveryInventory, records map[types.CanonicalRecordReference]types.CurrentRecord) (map[types.AppNamespace]types.CurrentAppRecordIndex, error) {
	value, err := call.Invoke(buildCurrentAppIndexesFunction, []any{inventory, records})
	if err != nil {
		var zero map[types.AppNamespace]types.CurrentAppRecordIndex
		return zero, err
	}
	return native.Output[map[types.AppNamespace]types.CurrentAppRecordIndex](buildCurrentAppIndexesFunction, value)
}

var buildCurrentAppRecordIndexFunction = native.Function{
	ID:        "artifact.base.current_record._build_current_app_record_index",
	Signature: "( app_namespace: AppNamespace, app: ConfiguredAppDiscovery, records: dict<CanonicalRecordReference, CurrentRecord> ) -> CurrentAppRecordIndex",
}

// BuildCurrentAppRecordIndex Builds one configured app index from every available physical artifact root and omits unavailable roots without treating them as empty artifact scopes.
func BuildCurrentAppRecordIndex(call native.Call, appNamespace types.AppNamespace, app types.ConfiguredAppDiscovery, records map[types.CanonicalRecordReference]types.CurrentRecord) (types.CurrentAppRecordIndex, error) {
	value, err := call.Invoke(buildCurrentAppRecordIndexFunction, []any{appNamespace, app, records})
	if err != nil {
		var zero types.CurrentAppRecordIndex
		return zero, err
	}
	return native.Output[types.CurrentAppRecordIndex](buildCurrentAppRecordIndexFunction, value)
}

var buildCurrentRecordStateFunction = native.Function{
	ID:        "artifact.base.current_record._build_current_record_state",
	Signature: "( repository_root: RepositoryRoot, inventory: RepositoryDiscoveryInventory, catalog: ArtifactModuleCatalog ) -> CurrentRecordState",
}

// BuildCurrentRecordState Composes capability-driven candidate collection, repository-wide uniqueness selection, and physical app-index construction into one immutable listing-MVP current-record state.
func BuildCurrentRecordState(call native.Call, repositoryRoot types.RepositoryRoot, inventory types.RepositoryDiscoveryInventory, catalog types.ArtifactModuleCatalog) (types.CurrentRecordState, error) {
	value, err := call.Invoke(buildCurrentRecordStateFunction, []any{repositoryRoot, inventory, catalog})
	if err != nil {
		var zero types.CurrentRecordState
		return zero, err
	}
	return native.Output[types.CurrentRecordState](buildCurrentRecordStateFunction, value)
}

var buildSequentialArtifactRecordIndexFunction = native.Function{
	ID:        "artifact.base.current_record._build_sequential_artifact_record_index",
	Signature: "( app_namespace: AppNamespace, declaration: SequentialArtifactModuleDeclaration, physical_tree: PhysicalDirectoryTree, records: dict<CanonicalRecordReference, CurrentRecord> ) -> SequentialArtifactRecordIndex",
}

// BuildSequentialArtifactRecordIndex Builds discovered sequential domain indexes from the retained physical tree, module segment declarations, and uniquely addressable records, including domains with no addressable record.
func BuildSequentialArtifactRecordIndex(call native.Call, appNamespace types.AppNamespace, declaration types.SequentialArtifactModuleDeclaration, physicalTree types.PhysicalDirectoryTree, records map[types.CanonicalRecordReference]types.CurrentRecord) (types.SequentialArtifactRecordIndex, error) {
	value, err := call.Invoke(buildSequentialArtifactRecordIndexFunction, []any{appNamespace, declaration, physicalTree, records})
	if err != nil {
		var zero types.SequentialArtifactRecordIndex
		return zero, err
	}
	return native.Output[types.SequentialArtifactRecordIndex](buildSequentialArtifactRecordIndexFunction, value)
}

var buildTreeArtifactRecordIndexFunction = native.Function{
	ID:        "artifact.base.current_record._build_tree_artifact_record_index",
	Signature: "( app_namespace: AppNamespace, declaration: TreeArtifactModuleDeclaration, physical_tree: PhysicalDirectoryTree, records: dict<CanonicalRecordReference, CurrentRecord> ) -> TreeArtifactRecordIndex",
}

// BuildTreeArtifactRecordIndex Builds one physical tree-node index independently of record admission and joins addressable records only through shared canonical references.
func BuildTreeArtifactRecordIndex(call native.Call, appNamespace types.AppNamespace, declaration types.TreeArtifactModuleDeclaration, physicalTree types.PhysicalDirectoryTree, records map[types.CanonicalRecordReference]types.CurrentRecord) (types.TreeArtifactRecordIndex, error) {
	value, err := call.Invoke(buildTreeArtifactRecordIndexFunction, []any{appNamespace, declaration, physicalTree, records})
	if err != nil {
		var zero types.TreeArtifactRecordIndex
		return zero, err
	}
	return native.Output[types.TreeArtifactRecordIndex](buildTreeArtifactRecordIndexFunction, value)
}

var collectAppCandidateClaimsFunction = native.Function{
	ID:        "artifact.base.current_record._collect_app_candidate_claims",
	Signature: "( repository_root: RepositoryRoot, app_namespace: AppNamespace, app: ConfiguredAppDiscovery, catalog: ArtifactModuleCatalog ) -> CurrentRecordCandidateClaims",
}

// CollectAppCandidateClaims Collects and merges claims from every available physical artifact root in one configured app using the catalog module with the same artifact-kind key.
func CollectAppCandidateClaims(call native.Call, repositoryRoot types.RepositoryRoot, appNamespace types.AppNamespace, app types.ConfiguredAppDiscovery, catalog types.ArtifactModuleCatalog) (types.CurrentRecordCandidateClaims, error) {
	value, err := call.Invoke(collectAppCandidateClaimsFunction, []any{repositoryRoot, appNamespace, app, catalog})
	if err != nil {
		var zero types.CurrentRecordCandidateClaims
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaims](collectAppCandidateClaimsFunction, value)
}

var collectArtifactCandidateClaimsFunction = native.Function{
	ID:        "artifact.base.current_record._collect_artifact_candidate_claims",
	Signature: "( repository_root: RepositoryRoot, app_namespace: AppNamespace, artifact_kind: ArtifactKind, artifact_root: ArtifactSourceRootDiscovery, module: ArtifactModule ) -> CurrentRecordCandidateClaims",
}

// CollectArtifactCandidateClaims Routes one available physical artifact root to the matching module capability and rejects any catalog-to-inventory structure disagreement.
func CollectArtifactCandidateClaims(call native.Call, repositoryRoot types.RepositoryRoot, appNamespace types.AppNamespace, artifactKind types.ArtifactKind, artifactRoot types.ArtifactSourceRootDiscovery, module types.ArtifactModule) (types.CurrentRecordCandidateClaims, error) {
	value, err := call.Invoke(collectArtifactCandidateClaimsFunction, []any{repositoryRoot, appNamespace, artifactKind, artifactRoot, module})
	if err != nil {
		var zero types.CurrentRecordCandidateClaims
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaims](collectArtifactCandidateClaimsFunction, value)
}

var collectCandidateClaimsFunction = native.Function{
	ID:        "artifact.base.current_record._collect_candidate_claims",
	Signature: "( repository_root: RepositoryRoot, inventory: RepositoryDiscoveryInventory, catalog: ArtifactModuleCatalog ) -> CurrentRecordCandidateClaims",
}

// CollectCandidateClaims Collects every configured app's candidate claims and merges them into one repository-wide canonical-identity grouping.
func CollectCandidateClaims(call native.Call, repositoryRoot types.RepositoryRoot, inventory types.RepositoryDiscoveryInventory, catalog types.ArtifactModuleCatalog) (types.CurrentRecordCandidateClaims, error) {
	value, err := call.Invoke(collectCandidateClaimsFunction, []any{repositoryRoot, inventory, catalog})
	if err != nil {
		var zero types.CurrentRecordCandidateClaims
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaims](collectCandidateClaimsFunction, value)
}

var collectSequentialArtifactCandidateClaimsFunction = native.Function{
	ID:        "artifact.base.current_record._collect_sequential_artifact_candidate_claims",
	Signature: "( repository_root: RepositoryRoot, app_namespace: AppNamespace, artifact_root: SequentialArtifactSourceRootDiscovery, function: SequentialFormCandidateFunction ) -> CurrentRecordCandidateClaims",
}

// CollectSequentialArtifactCandidateClaims Loads one sequential artifact root, invokes its resolved candidate capability for every source, skips expected non-candidates, and groups the formed claims.
func CollectSequentialArtifactCandidateClaims(call native.Call, repositoryRoot types.RepositoryRoot, appNamespace types.AppNamespace, artifactRoot types.SequentialArtifactSourceRootDiscovery, function types.SequentialFormCandidateFunction) (types.CurrentRecordCandidateClaims, error) {
	value, err := call.Invoke(collectSequentialArtifactCandidateClaimsFunction, []any{repositoryRoot, appNamespace, artifactRoot, function})
	if err != nil {
		var zero types.CurrentRecordCandidateClaims
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaims](collectSequentialArtifactCandidateClaimsFunction, value)
}

var collectTreeArtifactCandidateClaimsFunction = native.Function{
	ID:        "artifact.base.current_record._collect_tree_artifact_candidate_claims",
	Signature: "( repository_root: RepositoryRoot, app_namespace: AppNamespace, artifact_root: TreeArtifactSourceRootDiscovery, function: TreeFormCandidateFunction ) -> CurrentRecordCandidateClaims",
}

// CollectTreeArtifactCandidateClaims Loads one tree artifact root, invokes its resolved candidate capability for every source, skips expected non-candidates, and groups the formed claims.
func CollectTreeArtifactCandidateClaims(call native.Call, repositoryRoot types.RepositoryRoot, appNamespace types.AppNamespace, artifactRoot types.TreeArtifactSourceRootDiscovery, function types.TreeFormCandidateFunction) (types.CurrentRecordCandidateClaims, error) {
	value, err := call.Invoke(collectTreeArtifactCandidateClaimsFunction, []any{repositoryRoot, appNamespace, artifactRoot, function})
	if err != nil {
		var zero types.CurrentRecordCandidateClaims
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaims](collectTreeArtifactCandidateClaimsFunction, value)
}

var extractCurrentRecordSourceHeaderFunction = native.Function{
	ID:        "artifact.base.current_record._extract_current_record_source_header",
	Signature: "( document: MarkdownDocument ) -> CurrentRecordSourceHeader",
}

// ExtractCurrentRecordSourceHeader Projects reusable title, H1-adjacent metadata, and real H2 heading values from one parsed Markdown document without applying artifact-specific validation.
func ExtractCurrentRecordSourceHeader(call native.Call, document types.MarkdownDocument) (types.CurrentRecordSourceHeader, error) {
	value, err := call.Invoke(extractCurrentRecordSourceHeaderFunction, []any{document})
	if err != nil {
		var zero types.CurrentRecordSourceHeader
		return zero, err
	}
	return native.Output[types.CurrentRecordSourceHeader](extractCurrentRecordSourceHeaderFunction, value)
}

var formCandidateClaimFunction = native.Function{
	ID:        "artifact.base.current_record._form_candidate_claim",
	Signature: "( reference: ArtifactReference, source_path: RepositoryRelativeSourcePath, source_header: CurrentRecordSourceHeader ) -> CurrentRecordCandidateClaim",
}

// FormCandidateClaim Attaches canonical identity, retained source provenance, and reusable lightweight source projections to one structure-specific artifact candidate.
func FormCandidateClaim(call native.Call, reference types.ArtifactReference, sourcePath types.RepositoryRelativeSourcePath, sourceHeader types.CurrentRecordSourceHeader) (types.CurrentRecordCandidateClaim, error) {
	value, err := call.Invoke(formCandidateClaimFunction, []any{reference, sourcePath, sourceHeader})
	if err != nil {
		var zero types.CurrentRecordCandidateClaim
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaim](formCandidateClaimFunction, value)
}

var groupCandidateClaimsFunction = native.Function{
	ID:        "artifact.base.current_record._group_candidate_claims",
	Signature: "( claims: list<CurrentRecordCandidateClaim> ) -> CurrentRecordCandidateClaims",
}

// GroupCandidateClaims Groups one flat claim collection by canonical record identity without selecting a winner.
func GroupCandidateClaims(call native.Call, claims []types.CurrentRecordCandidateClaim) (types.CurrentRecordCandidateClaims, error) {
	value, err := call.Invoke(groupCandidateClaimsFunction, []any{claims})
	if err != nil {
		var zero types.CurrentRecordCandidateClaims
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaims](groupCandidateClaimsFunction, value)
}

var indexCurrentAppRecordIndexesFunction = native.Function{
	ID:        "artifact.base.current_record._index_current_app_record_indexes",
	Signature: "( entries: list<CurrentAppRecordIndexEntry> ) -> dict<AppNamespace, CurrentAppRecordIndex>",
}

// IndexCurrentAppRecordIndexes Indexes the complete configured app record-index entries by app namespace and rejects duplicate keys.
func IndexCurrentAppRecordIndexes(call native.Call, entries []types.CurrentAppRecordIndexEntry) (map[types.AppNamespace]types.CurrentAppRecordIndex, error) {
	value, err := call.Invoke(indexCurrentAppRecordIndexesFunction, []any{entries})
	if err != nil {
		var zero map[types.AppNamespace]types.CurrentAppRecordIndex
		return zero, err
	}
	return native.Output[map[types.AppNamespace]types.CurrentAppRecordIndex](indexCurrentAppRecordIndexesFunction, value)
}

var indexCurrentArtifactRecordIndexesFunction = native.Function{
	ID:        "artifact.base.current_record._index_current_artifact_record_indexes",
	Signature: "( entries: list<CurrentArtifactRecordIndexEntry> ) -> dict<ArtifactKind, CurrentArtifactRecordIndex>",
}

// IndexCurrentArtifactRecordIndexes Indexes one configured app's available structure-specific artifact index entries by artifact kind and rejects duplicate keys.
func IndexCurrentArtifactRecordIndexes(call native.Call, entries []types.CurrentArtifactRecordIndexEntry) (map[types.ArtifactKind]types.CurrentArtifactRecordIndex, error) {
	value, err := call.Invoke(indexCurrentArtifactRecordIndexesFunction, []any{entries})
	if err != nil {
		var zero map[types.ArtifactKind]types.CurrentArtifactRecordIndex
		return zero, err
	}
	return native.Output[map[types.ArtifactKind]types.CurrentArtifactRecordIndex](indexCurrentArtifactRecordIndexesFunction, value)
}

var loadSequentialCandidateSourcesFunction = native.Function{
	ID:        "artifact.base.current_record._load_sequential_candidate_sources",
	Signature: "( repository_root: RepositoryRoot, source_root: ArtifactSourceRootPath, physical_tree: PhysicalDirectoryTree ) -> list<SequentialCandidateSource>",
}

// LoadSequentialCandidateSources Returns every readable parsed Markdown source beneath one available sequential artifact root while preserving physical-domain and repository-relative provenance.
func LoadSequentialCandidateSources(call native.Call, repositoryRoot types.RepositoryRoot, sourceRoot types.ArtifactSourceRootPath, physicalTree types.PhysicalDirectoryTree) ([]types.SequentialCandidateSource, error) {
	value, err := call.Invoke(loadSequentialCandidateSourcesFunction, []any{repositoryRoot, sourceRoot, physicalTree})
	if err != nil {
		var zero []types.SequentialCandidateSource
		return zero, err
	}
	return native.Output[[]types.SequentialCandidateSource](loadSequentialCandidateSourcesFunction, value)
}

var loadTreeCandidateSourcesFunction = native.Function{
	ID:        "artifact.base.current_record._load_tree_candidate_sources",
	Signature: "( repository_root: RepositoryRoot, source_root: ArtifactSourceRootPath, physical_tree: PhysicalDirectoryTree ) -> list<TreeCandidateSource>",
}

// LoadTreeCandidateSources Returns every readable parsed Markdown source beneath one available tree artifact root while preserving artifact-relative and repository-relative provenance.
func LoadTreeCandidateSources(call native.Call, repositoryRoot types.RepositoryRoot, sourceRoot types.ArtifactSourceRootPath, physicalTree types.PhysicalDirectoryTree) ([]types.TreeCandidateSource, error) {
	value, err := call.Invoke(loadTreeCandidateSourcesFunction, []any{repositoryRoot, sourceRoot, physicalTree})
	if err != nil {
		var zero []types.TreeCandidateSource
		return zero, err
	}
	return native.Output[[]types.TreeCandidateSource](loadTreeCandidateSourcesFunction, value)
}

var mergeCandidateClaimCollectionsFunction = native.Function{
	ID:        "artifact.base.current_record._merge_candidate_claim_collections",
	Signature: "( collections: list<CurrentRecordCandidateClaims> ) -> CurrentRecordCandidateClaims",
}

// MergeCandidateClaimCollections Merges independently grouped claim collections while preserving every claim under its canonical record identity.
func MergeCandidateClaimCollections(call native.Call, collections []types.CurrentRecordCandidateClaims) (types.CurrentRecordCandidateClaims, error) {
	value, err := call.Invoke(mergeCandidateClaimCollectionsFunction, []any{collections})
	if err != nil {
		var zero types.CurrentRecordCandidateClaims
		return zero, err
	}
	return native.Output[types.CurrentRecordCandidateClaims](mergeCandidateClaimCollectionsFunction, value)
}

var rejectArtifactModuleDiscoveryMismatchFunction = native.Function{
	ID:        "artifact.base.current_record._reject_artifact_module_discovery_mismatch",
	Signature: "( artifact_kind: ArtifactKind ) -> never",
}

// RejectArtifactModuleDiscoveryMismatch Terminates current-record construction when an artifact module and its retained physical discovery use different structure variants.
func RejectArtifactModuleDiscoveryMismatch(call native.Call, artifactKind types.ArtifactKind) error {
	_, err := call.Invoke(rejectArtifactModuleDiscoveryMismatchFunction, []any{artifactKind})
	return err
}

var selectUniqueRecordsFunction = native.Function{
	ID:        "artifact.base.current_record._select_unique_records",
	Signature: "( claims: CurrentRecordCandidateClaims ) -> dict<CanonicalRecordReference, CurrentRecord>",
}

// SelectUniqueRecords Constructs addressable current records only for canonical identities having exactly one candidate claim and omits every conflicted identity without retaining conflict members.
func SelectUniqueRecords(call native.Call, claims types.CurrentRecordCandidateClaims) (map[types.CanonicalRecordReference]types.CurrentRecord, error) {
	value, err := call.Invoke(selectUniqueRecordsFunction, []any{claims})
	if err != nil {
		var zero map[types.CanonicalRecordReference]types.CurrentRecord
		return zero, err
	}
	return native.Output[map[types.CanonicalRecordReference]types.CurrentRecord](selectUniqueRecordsFunction, value)
}
