// Code generated by PuppyDSL. DO NOT EDIT.

package launch

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var getRepositoryRootFunction = native.Function{
	ID:        "drmcp_runtime.launch._get_repository_root",
	Signature: "() -> RepositoryRoot",
}

// GetRepositoryRoot Returns the normalized repository root supplied as the required DRMCP process launch argument.
func GetRepositoryRoot(call native.Call) (types.RepositoryRoot, error) {
	value, err := call.Invoke(getRepositoryRootFunction, nil)
	if err != nil {
		var zero types.RepositoryRoot
		return zero, err
	}
	return native.Output[types.RepositoryRoot](getRepositoryRootFunction, value)
}
