// Code generated by PuppyDSL. DO NOT EDIT.

package discovery

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var buildRepositoryDiscoveryInventoryFunction = native.Function{
	ID:        "artifact.base.discovery._build_repository_discovery_inventory",
	Signature: "( repository_root: RepositoryRoot, configuration: RepositoryConfiguration, catalog: ArtifactModuleCatalog ) -> RepositoryDiscoveryInventory",
}

// BuildRepositoryDiscoveryInventory Builds the keyed shared repository discovery inventory by applying every activated module declaration to every explicitly configured current source.
func BuildRepositoryDiscoveryInventory(call native.Call, repositoryRoot types.RepositoryRoot, configuration types.RepositoryConfiguration, catalog types.ArtifactModuleCatalog) (types.RepositoryDiscoveryInventory, error) {
	value, err := call.Invoke(buildRepositoryDiscoveryInventoryFunction, []any{repositoryRoot, configuration, catalog})
	if err != nil {
		var zero types.RepositoryDiscoveryInventory
		return zero, err
	}
	return native.Output[types.RepositoryDiscoveryInventory](buildRepositoryDiscoveryInventoryFunction, value)
}

var discoverArtifactRootEntryFunction = native.Function{
	ID:        "artifact.base.discovery._discover_artifact_root_entry",
	Signature: "( repository_root: RepositoryRoot, records_root: RecordsRoot, artifact_kind: ArtifactKind, module: ArtifactModule ) -> ArtifactSourceRootDiscoveryEntry",
}

// DiscoverArtifactRootEntry Routes one activated artifact module declaration to its structure-specific physical source-root discovery and preserves the catalog key.
func DiscoverArtifactRootEntry(call native.Call, repositoryRoot types.RepositoryRoot, recordsRoot types.RecordsRoot, artifactKind types.ArtifactKind, module types.ArtifactModule) (types.ArtifactSourceRootDiscoveryEntry, error) {
	value, err := call.Invoke(discoverArtifactRootEntryFunction, []any{repositoryRoot, recordsRoot, artifactKind, module})
	if err != nil {
		var zero types.ArtifactSourceRootDiscoveryEntry
		return zero, err
	}
	return native.Output[types.ArtifactSourceRootDiscoveryEntry](discoverArtifactRootEntryFunction, value)
}

var discoverConfiguredAppFunction = native.Function{
	ID:        "artifact.base.discovery._discover_configured_app",
	Signature: "( repository_root: RepositoryRoot, current_source: ConfiguredCurrentSource, catalog: ArtifactModuleCatalog ) -> ConfiguredAppDiscovery",
}

// DiscoverConfiguredApp Discovers every activated artifact module beneath one explicitly configured records root and indexes the results by artifact kind.
func DiscoverConfiguredApp(call native.Call, repositoryRoot types.RepositoryRoot, currentSource types.ConfiguredCurrentSource, catalog types.ArtifactModuleCatalog) (types.ConfiguredAppDiscovery, error) {
	value, err := call.Invoke(discoverConfiguredAppFunction, []any{repositoryRoot, currentSource, catalog})
	if err != nil {
		var zero types.ConfiguredAppDiscovery
		return zero, err
	}
	return native.Output[types.ConfiguredAppDiscovery](discoverConfiguredAppFunction, value)
}

var discoverSequentialArtifactRootFunction = native.Function{
	ID:        "artifact.base.discovery._discover_sequential_artifact_root",
	Signature: "( repository_root: RepositoryRoot, records_root: RecordsRoot, declaration: SequentialArtifactModuleDeclaration ) -> SequentialArtifactSourceRootDiscovery",
}

// DiscoverSequentialArtifactRoot Derives one sequential artifact source root from its module declaration and captures its physical Markdown-source directory tree when available.
func DiscoverSequentialArtifactRoot(call native.Call, repositoryRoot types.RepositoryRoot, recordsRoot types.RecordsRoot, declaration types.SequentialArtifactModuleDeclaration) (types.SequentialArtifactSourceRootDiscovery, error) {
	value, err := call.Invoke(discoverSequentialArtifactRootFunction, []any{repositoryRoot, recordsRoot, declaration})
	if err != nil {
		var zero types.SequentialArtifactSourceRootDiscovery
		return zero, err
	}
	return native.Output[types.SequentialArtifactSourceRootDiscovery](discoverSequentialArtifactRootFunction, value)
}

var discoverTreeArtifactRootFunction = native.Function{
	ID:        "artifact.base.discovery._discover_tree_artifact_root",
	Signature: "( repository_root: RepositoryRoot, records_root: RecordsRoot, declaration: TreeArtifactModuleDeclaration ) -> TreeArtifactSourceRootDiscovery",
}

// DiscoverTreeArtifactRoot Derives one tree artifact source root from its module declaration and captures its physical Markdown-source directory tree when available.
func DiscoverTreeArtifactRoot(call native.Call, repositoryRoot types.RepositoryRoot, recordsRoot types.RecordsRoot, declaration types.TreeArtifactModuleDeclaration) (types.TreeArtifactSourceRootDiscovery, error) {
	value, err := call.Invoke(discoverTreeArtifactRootFunction, []any{repositoryRoot, recordsRoot, declaration})
	if err != nil {
		var zero types.TreeArtifactSourceRootDiscovery
		return zero, err
	}
	return native.Output[types.TreeArtifactSourceRootDiscovery](discoverTreeArtifactRootFunction, value)
}

var indexArtifactRootDiscoveriesFunction = native.Function{
	ID:        "artifact.base.discovery._index_artifact_root_discoveries",
	Signature: "( entries: list<ArtifactSourceRootDiscoveryEntry> ) -> dict<ArtifactKind, ArtifactSourceRootDiscovery>",
}

// IndexArtifactRootDiscoveries Indexes one complete set of artifact-root discovery entries by artifact kind and rejects duplicate keys.
func IndexArtifactRootDiscoveries(call native.Call, entries []types.ArtifactSourceRootDiscoveryEntry) (map[types.ArtifactKind]types.ArtifactSourceRootDiscovery, error) {
	value, err := call.Invoke(indexArtifactRootDiscoveriesFunction, []any{entries})
	if err != nil {
		var zero map[types.ArtifactKind]types.ArtifactSourceRootDiscovery
		return zero, err
	}
	return native.Output[map[types.ArtifactKind]types.ArtifactSourceRootDiscovery](indexArtifactRootDiscoveriesFunction, value)
}

var indexConfiguredAppDiscoveriesFunction = native.Function{
	ID:        "artifact.base.discovery._index_configured_app_discoveries",
	Signature: "( entries: list<ConfiguredAppDiscoveryEntry> ) -> dict<AppNamespace, ConfiguredAppDiscovery>",
}

// IndexConfiguredAppDiscoveries Indexes one complete set of configured app discovery entries by app namespace and rejects duplicate keys.
func IndexConfiguredAppDiscoveries(call native.Call, entries []types.ConfiguredAppDiscoveryEntry) (map[types.AppNamespace]types.ConfiguredAppDiscovery, error) {
	value, err := call.Invoke(indexConfiguredAppDiscoveriesFunction, []any{entries})
	if err != nil {
		var zero map[types.AppNamespace]types.ConfiguredAppDiscovery
		return zero, err
	}
	return native.Output[map[types.AppNamespace]types.ConfiguredAppDiscovery](indexConfiguredAppDiscoveriesFunction, value)
}

var isArtifactSourceRootAvailableFunction = native.Function{
	ID:        "artifact.base.discovery._is_artifact_source_root_available",
	Signature: "( discovery: ArtifactSourceRootDiscovery ) -> boolean",
}

// IsArtifactSourceRootAvailable Reports the retained availability state of one structure-specific artifact source-root discovery.
func IsArtifactSourceRootAvailable(call native.Call, discovery types.ArtifactSourceRootDiscovery) (bool, error) {
	value, err := call.Invoke(isArtifactSourceRootAvailableFunction, []any{discovery})
	if err != nil {
		var zero bool
		return zero, err
	}
	return native.Output[bool](isArtifactSourceRootAvailableFunction, value)
}
