// Code generated by PuppyDSL. DO NOT EDIT.

package module

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var invokeSequentialFormCandidateFunction = native.Function{
	ID:        "artifact.base.module._invoke_sequential_form_candidate",
	Signature: "( function: SequentialFormCandidateFunction, app_namespace: AppNamespace, physical_domain: PhysicalDirectoryName, document: MarkdownDocument ) -> SequentialFormCandidateOutcome",
}

// InvokeSequentialFormCandidate Invokes one bootstrap-resolved sequential candidate-formation capability for a parsed Markdown source in its app and physical-domain scope.
func InvokeSequentialFormCandidate(call native.Call, function types.SequentialFormCandidateFunction, appNamespace types.AppNamespace, physicalDomain types.PhysicalDirectoryName, document types.MarkdownDocument) (types.SequentialFormCandidateOutcome, error) {
	value, err := call.Invoke(invokeSequentialFormCandidateFunction, []any{function, appNamespace, physicalDomain, document})
	if err != nil {
		var zero types.SequentialFormCandidateOutcome
		return zero, err
	}
	return native.Output[types.SequentialFormCandidateOutcome](invokeSequentialFormCandidateFunction, value)
}

var invokeTreeFormCandidateFunction = native.Function{
	ID:        "artifact.base.module._invoke_tree_form_candidate",
	Signature: "( function: TreeFormCandidateFunction, app_namespace: AppNamespace, markdown_path: ArtifactRelativeMarkdownPath, document: MarkdownDocument ) -> TreeFormCandidateOutcome",
}

// InvokeTreeFormCandidate Invokes one bootstrap-resolved tree candidate-formation capability for a parsed Markdown source identified by its artifact-relative path.
func InvokeTreeFormCandidate(call native.Call, function types.TreeFormCandidateFunction, appNamespace types.AppNamespace, markdownPath types.ArtifactRelativeMarkdownPath, document types.MarkdownDocument) (types.TreeFormCandidateOutcome, error) {
	value, err := call.Invoke(invokeTreeFormCandidateFunction, []any{function, appNamespace, markdownPath, document})
	if err != nil {
		var zero types.TreeFormCandidateOutcome
		return zero, err
	}
	return native.Output[types.TreeFormCandidateOutcome](invokeTreeFormCandidateFunction, value)
}
