// Code generated by PuppyDSL. DO NOT EDIT.

package manifest

import yaml "gopkg.in/yaml.v3"

// Document is one build-time-bound application manifest.
type Document struct {
	BindName string
	Source   string
	Root     yaml.Node
}

// Fingerprint identifies the exact sorted .manifest.yaml source set used for generation.
const Fingerprint = "c111c43421bb3eadf7bd85b71336e328a03312cc950c86c69b6fc090381d3fee"

// McpTools is the manifest bound as "mcp_tools".
var McpTools = Document{
	BindName: "mcp_tools",
	Source:   "manifests/mcp/tools.manifest.yaml",
	Root:     buildMcpToolsRoot(),
}

var documentsByBindName = map[string]Document{
	"mcp_tools": McpTools,
}

// ByBindName resolves one generated manifest by its exact bind name.
func ByBindName(name string) (Document, bool) {
	document, exists := documentsByBindName[name]
	return document, exists
}

func buildMcpToolsRoot() yaml.Node {
	nodes := make([]yaml.Node, 27)
	nodes[0] = yaml.Node{
		Kind:        yaml.Kind(4),
		Style:       yaml.Style(0),
		Tag:         "!!map",
		Value:       "",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        12,
		Column:      1,
	}
	nodes[1] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "tools",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        12,
		Column:      1,
	}
	nodes[2] = yaml.Node{
		Kind:        yaml.Kind(4),
		Style:       yaml.Style(0),
		Tag:         "!!map",
		Value:       "",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        13,
		Column:      3,
	}
	nodes[3] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "discover_record_scopes",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        13,
		Column:      3,
	}
	nodes[4] = yaml.Node{
		Kind:        yaml.Kind(4),
		Style:       yaml.Style(0),
		Tag:         "!!map",
		Value:       "",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        14,
		Column:      5,
	}
	nodes[5] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "detail",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        14,
		Column:      5,
	}
	nodes[6] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "Discovers configured app, artifact-kind, sequential-domain, or tree-root scopes according to one exact selector combination.",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        14,
		Column:      13,
	}
	nodes[7] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "function",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        15,
		Column:      5,
	}
	nodes[8] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "operation.discovery_and_listing.discover_record_scopes",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        15,
		Column:      15,
	}
	nodes[9] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "list_sequential_records",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        17,
		Column:      3,
	}
	nodes[10] = yaml.Node{
		Kind:        yaml.Kind(4),
		Style:       yaml.Style(0),
		Tag:         "!!map",
		Value:       "",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        18,
		Column:      5,
	}
	nodes[11] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "detail",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        18,
		Column:      5,
	}
	nodes[12] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "Lists one bounded ordered range of uniquely addressable current records within an exact sequential app, artifact-kind, and domain scope.",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        18,
		Column:      13,
	}
	nodes[13] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "function",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        19,
		Column:      5,
	}
	nodes[14] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "operation.discovery_and_listing.list_sequential_records",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        19,
		Column:      15,
	}
	nodes[15] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "list_tree_children",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        21,
		Column:      3,
	}
	nodes[16] = yaml.Node{
		Kind:        yaml.Kind(4),
		Style:       yaml.Style(0),
		Tag:         "!!map",
		Value:       "",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        22,
		Column:      5,
	}
	nodes[17] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "detail",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        22,
		Column:      5,
	}
	nodes[18] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "Lists one bounded range of direct current tree children for an exact canonical tree-node selector or reports the normal terminal-node result.",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        22,
		Column:      13,
	}
	nodes[19] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "function",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        23,
		Column:      5,
	}
	nodes[20] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "operation.discovery_and_listing.list_tree_children",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        23,
		Column:      15,
	}
	nodes[21] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "inspect_tree",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        25,
		Column:      3,
	}
	nodes[22] = yaml.Node{
		Kind:        yaml.Kind(4),
		Style:       yaml.Style(0),
		Tag:         "!!map",
		Value:       "",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        26,
		Column:      5,
	}
	nodes[23] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "detail",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        26,
		Column:      5,
	}
	nodes[24] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "Inspects one exact current tree subtree through bounded breadth-first selection and returns a nested structural overview.",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        26,
		Column:      13,
	}
	nodes[25] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "function",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        27,
		Column:      5,
	}
	nodes[26] = yaml.Node{
		Kind:        yaml.Kind(8),
		Style:       yaml.Style(0),
		Tag:         "!!str",
		Value:       "operation.discovery_and_listing.inspect_tree",
		Anchor:      "",
		HeadComment: "",
		LineComment: "",
		FootComment: "",
		Line:        27,
		Column:      15,
	}
	nodes[0].Content = []*yaml.Node{&nodes[1], &nodes[2]}
	nodes[2].Content = []*yaml.Node{&nodes[3], &nodes[4], &nodes[9], &nodes[10], &nodes[15], &nodes[16], &nodes[21], &nodes[22]}
	nodes[4].Content = []*yaml.Node{&nodes[5], &nodes[6], &nodes[7], &nodes[8]}
	nodes[10].Content = []*yaml.Node{&nodes[11], &nodes[12], &nodes[13], &nodes[14]}
	nodes[16].Content = []*yaml.Node{&nodes[17], &nodes[18], &nodes[19], &nodes[20]}
	nodes[22].Content = []*yaml.Node{&nodes[23], &nodes[24], &nodes[25], &nodes[26]}
	return nodes[0]
}
