// Code generated by PuppyDSL. DO NOT EDIT.

package types

// AcceptedSelectorCombinationsContext Carries every selector field-name combination accepted by one operation in selector-progression order.
type AcceptedSelectorCombinationsContext struct {
	AcceptedSelectorCombinations [][]string `json:"accepted_selector_combinations" yaml:"accepted_selector_combinations"`
}

func (AcceptedSelectorCombinationsContext) isOperationDiagnosticContext() {}

func (AcceptedSelectorCombinationsContext) isRecordScopeDiscoverySelectorRoute() {}

// AppNamespace Identifies the application, subsystem, or cross-application scope that owns Design Records.
type AppNamespace string

// AppScope Identifies one configured app scope exposed by record-scope discovery.
type AppScope struct {
	AppNamespace AppNamespace `json:"app_namespace" yaml:"app_namespace"`
}

// AppScopes Contains every configured app scope in ascending app-namespace order.
type AppScopes struct {
	AppScopes []AppScope `json:"app_scopes" yaml:"app_scopes"`
}

func (AppScopes) isRecordScopeDiscoveryOutcome() {}

// AppScopesRoute Selects discovery of every configured app scope when neither selector is supplied.
type AppScopesRoute string

const (
	AppScopesRouteSelected AppScopesRoute = "selected"
)

func (AppScopesRoute) isRecordScopeDiscoverySelectorRoute() {}

// ArtifactDirectory Identifies one artifact source directory segment relative to a configured records root.
type ArtifactDirectory string

// ArtifactKind Identifies one semantic Design Record artifact kind used for module and operation routing independently of canonical-reference discriminator literals.
type ArtifactKind string

// ArtifactKindScope Identifies one available artifact kind and its declared record structure within a configured app.
type ArtifactKindScope struct {
	ArtifactKind    ArtifactKind    `json:"artifact_kind" yaml:"artifact_kind"`
	RecordStructure RecordStructure `json:"record_structure" yaml:"record_structure"`
}

// ArtifactKindScopes Contains every available artifact-kind scope for one configured app in ascending artifact-kind order.
type ArtifactKindScopes struct {
	ArtifactKindScopes []ArtifactKindScope `json:"artifact_kind_scopes" yaml:"artifact_kind_scopes"`
}

func (ArtifactKindScopes) isRecordScopeDiscoveryOutcome() {}

// ArtifactKindScopesRoute Selects available artifact kinds for one supplied app namespace.
type ArtifactKindScopesRoute struct {
	AppNamespace AppNamespace `json:"app_namespace" yaml:"app_namespace"`
}

func (ArtifactKindScopesRoute) isRecordScopeDiscoverySelectorRoute() {}

// ArtifactModule Carries one structure-specific activated artifact module registration.
type ArtifactModule interface {
	isArtifactModule()
}

// ArtifactModuleCatalog Contains the activated artifact modules keyed by their unique semantic artifact kind.
type ArtifactModuleCatalog struct {
	Modules map[ArtifactKind]ArtifactModule `json:"modules" yaml:"modules"`
}

// ArtifactReference Carries one structure-specific artifact-module-confirmed canonical reference.
type ArtifactReference interface {
	isArtifactReference()
}

// ArtifactRelativeMarkdownPath Identifies one normalized Markdown source path relative to its artifact source root.
type ArtifactRelativeMarkdownPath string

// ArtifactRootSelectionOutcome Carries either the selected structure-specific artifact root or the shared unavailable-kind context required to form an operation diagnostic.
type ArtifactRootSelectionOutcome interface {
	isArtifactRootSelectionOutcome()
}

// ArtifactScopeRoute Selects the structure-specific scope for one supplied app namespace and artifact kind.
type ArtifactScopeRoute struct {
	AppNamespace AppNamespace `json:"app_namespace" yaml:"app_namespace"`
	ArtifactKind ArtifactKind `json:"artifact_kind" yaml:"artifact_kind"`
}

func (ArtifactScopeRoute) isRecordScopeDiscoverySelectorRoute() {}

// ArtifactSourceRootDiscovery Carries one structure-specific artifact source-root discovery result.
type ArtifactSourceRootDiscovery interface {
	isArtifactSourceRootDiscovery()
}

// ArtifactSourceRootDiscoveryEntry Carries one artifact-kind key together with the structure-specific source-root discovery constructed for that module.
type ArtifactSourceRootDiscoveryEntry struct {
	ArtifactKind ArtifactKind                `json:"artifact_kind" yaml:"artifact_kind"`
	Discovery    ArtifactSourceRootDiscovery `json:"discovery" yaml:"discovery"`
}

// ArtifactSourceRootPath Identifies one artifact source root path derived from a configured records root and artifact directory.
type ArtifactSourceRootPath string

// BoundedIntegerContext Carries the accepted inclusive integer bounds, default, and exact supplied value for one bounded request field.
type BoundedIntegerContext struct {
	Minimum int64 `json:"minimum" yaml:"minimum"`
	Maximum int64 `json:"maximum" yaml:"maximum"`
	Default int64 `json:"default" yaml:"default"`
	Actual  int64 `json:"actual" yaml:"actual"`
}

func (BoundedIntegerContext) isOperationDiagnosticContext() {}

func (BoundedIntegerContext) isSequentialRecordListingRequestValidationOutcome() {}

func (BoundedIntegerContext) isTreeChildListingRequestValidationOutcome() {}

// CandidateNotFormed Indicates that one readable Markdown source did not form a listing candidate under the selected artifact module contract.
type CandidateNotFormed struct {
}

func (CandidateNotFormed) isSequentialFormCandidateOutcome() {}

func (CandidateNotFormed) isTreeFormCandidateOutcome() {}

// CanonicalRecordReference Identifies one canonical Design Record identity, including a current tree node that may have no corresponding addressable record.
type CanonicalRecordReference string

// ConfiguredAppDiscovery Groups the keyed artifact source-root discoveries derived for one explicitly configured current source.
type ConfiguredAppDiscovery struct {
	RecordsRoot   RecordsRoot                                  `json:"records_root" yaml:"records_root"`
	ArtifactRoots map[ArtifactKind]ArtifactSourceRootDiscovery `json:"artifact_roots" yaml:"artifact_roots"`
}

func (ConfiguredAppDiscovery) isConfiguredAppSelectionOutcome() {}

// ConfiguredAppDiscoveryEntry Carries one configured app-namespace key together with its complete physical artifact-root discovery.
type ConfiguredAppDiscoveryEntry struct {
	AppNamespace AppNamespace           `json:"app_namespace" yaml:"app_namespace"`
	Discovery    ConfiguredAppDiscovery `json:"discovery" yaml:"discovery"`
}

// ConfiguredAppSelectionOutcome Carries either the selected configured app discovery or the shared unavailable-app context required to form an operation diagnostic.
type ConfiguredAppSelectionOutcome interface {
	isConfiguredAppSelectionOutcome()
}

// ConfiguredCurrentSource Associates one app namespace with the repository-relative records root used as its current Design Records discovery boundary.
type ConfiguredCurrentSource struct {
	AppNamespace AppNamespace `json:"app_namespace" yaml:"app_namespace"`
	RecordsRoot  RecordsRoot  `json:"records_root" yaml:"records_root"`
}

// CurrentAppRecordIndex Contains every available artifact-kind current-record index within one configured app scope.
type CurrentAppRecordIndex struct {
	Artifacts map[ArtifactKind]CurrentArtifactRecordIndex `json:"artifacts" yaml:"artifacts"`
}

func (CurrentAppRecordIndex) isSequentialListingAppSelectionOutcome() {}

// CurrentAppRecordIndexEntry Carries one configured app-namespace key together with its complete current artifact index.
type CurrentAppRecordIndexEntry struct {
	AppNamespace AppNamespace          `json:"app_namespace" yaml:"app_namespace"`
	Index        CurrentAppRecordIndex `json:"index" yaml:"index"`
}

// CurrentArtifactRecordIndex Carries one structure-specific current-record index for an available artifact kind.
type CurrentArtifactRecordIndex interface {
	isCurrentArtifactRecordIndex()
}

// CurrentArtifactRecordIndexEntry Carries one available artifact-kind key together with its structure-specific current-record index.
type CurrentArtifactRecordIndexEntry struct {
	ArtifactKind ArtifactKind               `json:"artifact_kind" yaml:"artifact_kind"`
	Index        CurrentArtifactRecordIndex `json:"index" yaml:"index"`
}

// CurrentRecord Carries one uniquely addressable admitted current record and the data required to identify, locate, and project it.
type CurrentRecord struct {
	Reference    ArtifactReference            `json:"reference" yaml:"reference"`
	CanonicalRef CanonicalRecordReference     `json:"canonical_ref" yaml:"canonical_ref"`
	SourcePath   RepositoryRelativeSourcePath `json:"source_path" yaml:"source_path"`
	SourceHeader CurrentRecordSourceHeader    `json:"source_header" yaml:"source_header"`
}

// CurrentRecordCandidateClaim Carries one artifact-module candidate together with canonical identity, repository-relative source provenance, and reusable lightweight source projections attached by current-record construction.
type CurrentRecordCandidateClaim struct {
	Reference    ArtifactReference            `json:"reference" yaml:"reference"`
	CanonicalRef CanonicalRecordReference     `json:"canonical_ref" yaml:"canonical_ref"`
	SourcePath   RepositoryRelativeSourcePath `json:"source_path" yaml:"source_path"`
	SourceHeader CurrentRecordSourceHeader    `json:"source_header" yaml:"source_header"`
}

// CurrentRecordCandidateClaims Groups every formed current-record candidate claim by canonical record identity for repository-wide uniqueness selection.
type CurrentRecordCandidateClaims struct {
	ByCanonicalRef map[CanonicalRecordReference][]CurrentRecordCandidateClaim `json:"by_canonical_ref" yaml:"by_canonical_ref"`
}

// CurrentRecordMetadata Carries successfully projected H1-adjacent metadata fields separated by source value form without applying artifact-specific validation.
type CurrentRecordMetadata struct {
	ScalarFields map[string]string   `json:"scalar_fields" yaml:"scalar_fields"`
	ListFields   map[string][]string `json:"list_fields" yaml:"list_fields"`
}

// CurrentRecordSourceHeader Carries reusable lightweight Markdown projections retained for current-record operations without complete source content or artifact-specific validation.
type CurrentRecordSourceHeader struct {
	Title      *string                `json:"title" yaml:"title"`
	Metadata   *CurrentRecordMetadata `json:"metadata" yaml:"metadata"`
	H2Headings *[]string              `json:"h2_headings" yaml:"h2_headings"`
}

// CurrentRecordState Contains every uniquely addressable current record and the configured app indexes used to select sequential scopes and current tree nodes.
type CurrentRecordState struct {
	Records map[CanonicalRecordReference]CurrentRecord `json:"records" yaml:"records"`
	Apps    map[AppNamespace]CurrentAppRecordIndex     `json:"apps" yaml:"apps"`
}

// CurrentTreeNode Carries one available current tree node and its direct canonical child relations independently of corresponding record admission.
type CurrentTreeNode struct {
	Segment  TreeNodeSegment                              `json:"segment" yaml:"segment"`
	Children map[TreeNodeSegment]CanonicalRecordReference `json:"children" yaml:"children"`
}

// CurrentTreeNodeSelectionOutcome Carries either one selected current tree node or the shared node-not-found context for the exact supplied selector.
type CurrentTreeNodeSelectionOutcome interface {
	isCurrentTreeNodeSelectionOutcome()
}

// DomainNamespace Identifies one concern area within an app namespace.
type DomainNamespace string

// DomainScope Identifies one discovered sequential domain scope.
type DomainScope struct {
	DomainNamespace DomainNamespace `json:"domain_namespace" yaml:"domain_namespace"`
}

// DomainScopes Contains every discovered domain scope for one sequential artifact kind in ascending domain-namespace order.
type DomainScopes struct {
	DomainScopes []DomainScope `json:"domain_scopes" yaml:"domain_scopes"`
}

func (DomainScopes) isRecordScopeDiscoveryOutcome() {}

// InvalidProjectionContext Carries unknown supplied projection values in request occurrence order and every accepted projection value in canonical order.
type InvalidProjectionContext struct {
	InvalidProjectionValues   []string `json:"invalid_projection_values" yaml:"invalid_projection_values"`
	AvailableProjectionValues []string `json:"available_projection_values" yaml:"available_projection_values"`
}

func (InvalidProjectionContext) isOperationDiagnosticContext() {}

func (InvalidProjectionContext) isSequentialRecordListingRequestValidationOutcome() {}

func (InvalidProjectionContext) isTreeChildListingRequestValidationOutcome() {}

// InvalidTreeNodeSelectorContext Carries one supplied node reference rejected as a tree selector and every accepted tree record-kind discriminator in canonical order.
type InvalidTreeNodeSelectorContext struct {
	NodeRef                 CanonicalRecordReference     `json:"node_ref" yaml:"node_ref"`
	AcceptedTreeRecordKinds []TreeReferenceDiscriminator `json:"accepted_tree_record_kinds" yaml:"accepted_tree_record_kinds"`
}

func (InvalidTreeNodeSelectorContext) isOperationDiagnosticContext() {}

func (InvalidTreeNodeSelectorContext) isTreeChildListingRequestValidationOutcome() {}

func (InvalidTreeNodeSelectorContext) isTreeOverviewRequestValidationOutcome() {}

// InvalidTreeOverviewDepth Distinguishes an invalid tree-overview depth from other request fields that use the shared bounded-integer diagnostic context shape.
type InvalidTreeOverviewDepth struct {
	Context BoundedIntegerContext `json:"context" yaml:"context"`
}

func (InvalidTreeOverviewDepth) isTreeOverviewRequestValidationOutcome() {}

// InvalidTreeOverviewNodeLimit Distinguishes an invalid tree-overview node limit from other request fields that use the shared bounded-integer diagnostic context shape.
type InvalidTreeOverviewNodeLimit struct {
	Context BoundedIntegerContext `json:"context" yaml:"context"`
}

func (InvalidTreeOverviewNodeLimit) isTreeOverviewRequestValidationOutcome() {}

// MarkdownDocument Represents one parsed Markdown document whose internal syntax-tree representation remains hidden from design-facing YAML.
type MarkdownDocument struct {
	value any
}

// MarkdownSourceFileName Identifies one Markdown source file name relative to its physical parent directory.
type MarkdownSourceFileName string

// MinimumIntegerContext Carries the accepted integer minimum, default, and exact supplied value for one lower-bounded request field.
type MinimumIntegerContext struct {
	Minimum int64 `json:"minimum" yaml:"minimum"`
	Default int64 `json:"default" yaml:"default"`
	Actual  int64 `json:"actual" yaml:"actual"`
}

func (MinimumIntegerContext) isOperationDiagnosticContext() {}

func (MinimumIntegerContext) isSequentialRecordListingRequestValidationOutcome() {}

func (MinimumIntegerContext) isTreeChildListingRequestValidationOutcome() {}

// MissingSelectorFieldsContext Carries required selector field names omitted from one schema-valid operation request in operation request-field order.
type MissingSelectorFieldsContext struct {
	MissingSelectorFields []string `json:"missing_selector_fields" yaml:"missing_selector_fields"`
}

func (MissingSelectorFieldsContext) isOperationDiagnosticContext() {}

func (MissingSelectorFieldsContext) isSequentialRecordListingRequestValidationOutcome() {}

// OperationDiagnostic Carries one expected operation error code, human-readable message, and required code-specific context.
type OperationDiagnostic struct {
	Code    OperationDiagnosticCode    `json:"code" yaml:"code"`
	Message string                     `json:"message" yaml:"message"`
	Context OperationDiagnosticContext `json:"context" yaml:"context"`
}

// OperationDiagnosticCode Identifies one expected request or current-state error exposed by the completed Discovery and Listing operations.
type OperationDiagnosticCode string

const (
	OperationDiagnosticCodeInvalidSelector   OperationDiagnosticCode = "invalid_selector"
	OperationDiagnosticCodeInvalidProjection OperationDiagnosticCode = "invalid_projection"
	OperationDiagnosticCodeInvalidLimit      OperationDiagnosticCode = "invalid_limit"
	OperationDiagnosticCodeInvalidOffset     OperationDiagnosticCode = "invalid_offset"
	OperationDiagnosticCodeInvalidDepth      OperationDiagnosticCode = "invalid_depth"
	OperationDiagnosticCodeInvalidNodeLimit  OperationDiagnosticCode = "invalid_node_limit"
	OperationDiagnosticCodeNodeNotFound      OperationDiagnosticCode = "node_not_found"
)

// OperationDiagnosticContext Carries exactly one context shape permitted by an expected Discovery and Listing diagnostic code.
type OperationDiagnosticContext interface {
	isOperationDiagnosticContext()
}

// OperationErrorResponse Carries exactly one expected top-level operation diagnostic and no partial success result.
type OperationErrorResponse struct {
	Error OperationDiagnostic `json:"error" yaml:"error"`
}

func (OperationErrorResponse) isRecordScopeDiscoveryOutcome() {}

func (OperationErrorResponse) isSequentialRecordListingOutcome() {}

func (OperationErrorResponse) isTreeChildListingOutcome() {}

func (OperationErrorResponse) isTreeOverviewOutcome() {}

// PhysicalDirectoryName Identifies one directory name relative to its physical parent directory.
type PhysicalDirectoryName string

// PhysicalDirectoryTree Preserves the nested physical directory and Markdown-source structure beneath one externally identified root directory.
type PhysicalDirectoryTree struct {
	Directories     map[PhysicalDirectoryName]PhysicalDirectoryTree `json:"directories" yaml:"directories"`
	MarkdownSources []MarkdownSourceFileName                        `json:"markdown_sources" yaml:"markdown_sources"`
}

// RecordScopeDiscoveryOutcome Carries one successful record-scope result or one shared top-level operation error response.
type RecordScopeDiscoveryOutcome interface {
	isRecordScopeDiscoveryOutcome()
}

// RecordScopeDiscoveryRequest Carries the optional app and artifact-kind selectors accepted by record-scope discovery.
type RecordScopeDiscoveryRequest struct {
	AppNamespace *AppNamespace `json:"app_namespace" yaml:"app_namespace"`
	ArtifactKind *ArtifactKind `json:"artifact_kind" yaml:"artifact_kind"`
}

// RecordScopeDiscoverySelectorRoute Carries the typed route or shared accepted-selector-combinations context derived from one request before repository inventory selection.
type RecordScopeDiscoverySelectorRoute interface {
	isRecordScopeDiscoverySelectorRoute()
}

// RecordStructure Identifies the physical and logical organization used by one artifact kind.
type RecordStructure string

const (
	RecordStructureSequential RecordStructure = "sequential"
	RecordStructureTree       RecordStructure = "tree"
)

// RecordsRoot Identifies one normalized repository-relative Design Records root.
type RecordsRoot string

// RepositoryConfiguration Contains the complete configured current source set used by runtime operations.
type RepositoryConfiguration struct {
	CurrentSources []ConfiguredCurrentSource `json:"current_sources" yaml:"current_sources"`
}

// RepositoryDiscoveryInventory Contains the keyed physical artifact source-root inventory for every explicitly configured app namespace.
type RepositoryDiscoveryInventory struct {
	Apps map[AppNamespace]ConfiguredAppDiscovery `json:"apps" yaml:"apps"`
}

// RepositoryRelativeSourcePath Identifies one current source path relative to the configured repository root for retained provenance and source access.
type RepositoryRelativeSourcePath string

// RepositoryRoot Identifies the normalized filesystem root supplied when the DRMCP process starts.
type RepositoryRoot string

// SelectedCurrentTreeNode Carries one selected current tree index and its exact current node for operation-specific navigation or traversal.
type SelectedCurrentTreeNode struct {
	Tree TreeArtifactRecordIndex `json:"tree" yaml:"tree"`
	Node CurrentTreeNode         `json:"node" yaml:"node"`
}

func (SelectedCurrentTreeNode) isCurrentTreeNodeSelectionOutcome() {}

// SequentialArtifactCandidate Carries one sequential artifact reference formed from one Markdown source under the selected artifact module contract.
type SequentialArtifactCandidate struct {
	Reference SequentialArtifactReference `json:"reference" yaml:"reference"`
}

func (SequentialArtifactCandidate) isSequentialFormCandidateOutcome() {}

// SequentialArtifactModule Joins the manifest-derived declaration and bootstrap-resolved capabilities for one sequential artifact kind.
type SequentialArtifactModule struct {
	Declaration  SequentialArtifactModuleDeclaration  `json:"declaration" yaml:"declaration"`
	Capabilities SequentialArtifactModuleCapabilities `json:"capabilities" yaml:"capabilities"`
}

func (SequentialArtifactModule) isArtifactModule() {}

// SequentialArtifactModuleCapabilities Carries the bootstrap-resolved executable capabilities registered for one sequential artifact kind.
type SequentialArtifactModuleCapabilities struct {
	FormCandidate SequentialFormCandidateFunction `json:"form_candidate" yaml:"form_candidate"`
}

// SequentialArtifactModuleDeclaration Carries the manifest-derived identity, source-placement, routing, and ordered segment declarations for one sequential artifact kind.
type SequentialArtifactModuleDeclaration struct {
	ArtifactKind           ArtifactKind                     `json:"artifact_kind" yaml:"artifact_kind"`
	ArtifactDirectory      ArtifactDirectory                `json:"artifact_directory" yaml:"artifact_directory"`
	ReferenceDiscriminator SequentialReferenceDiscriminator `json:"reference_discriminator" yaml:"reference_discriminator"`
	Segments               []SequentialSegmentDeclaration   `json:"segments" yaml:"segments"`
}

// SequentialArtifactRecordIndex Contains every discovered sequential domain for one available artifact kind, including domains with no addressable current record.
type SequentialArtifactRecordIndex struct {
	Domains map[DomainNamespace]SequentialDomainRecordIndex `json:"domains" yaml:"domains"`
}

func (SequentialArtifactRecordIndex) isCurrentArtifactRecordIndex() {}

func (SequentialArtifactRecordIndex) isSequentialListingArtifactSelectionOutcome() {}

// SequentialArtifactReference Carries one confirmed sequential reference with its semantic artifact-specific segments named by the selected artifact module.
type SequentialArtifactReference struct {
	AppNamespace    AppNamespace                     `json:"app_namespace" yaml:"app_namespace"`
	ArtifactKind    ArtifactKind                     `json:"artifact_kind" yaml:"artifact_kind"`
	DomainNamespace DomainNamespace                  `json:"domain_namespace" yaml:"domain_namespace"`
	Segments        map[SequentialSegmentName]string `json:"segments" yaml:"segments"`
}

func (SequentialArtifactReference) isArtifactReference() {}

// SequentialArtifactSourceRootDiscovery Carries one sequential artifact kind's source-root availability and physical tree together with the manifest-derived module declaration used to discover it.
type SequentialArtifactSourceRootDiscovery struct {
	Declaration  SequentialArtifactModuleDeclaration `json:"declaration" yaml:"declaration"`
	SourceRoot   ArtifactSourceRootPath              `json:"source_root" yaml:"source_root"`
	Available    bool                                `json:"available" yaml:"available"`
	PhysicalTree PhysicalDirectoryTree               `json:"physical_tree" yaml:"physical_tree"`
}

func (SequentialArtifactSourceRootDiscovery) isArtifactRootSelectionOutcome() {}

func (SequentialArtifactSourceRootDiscovery) isArtifactSourceRootDiscovery() {}

// SequentialCandidateSource Carries one parsed Markdown source together with its physical sequential domain and repository-relative provenance.
type SequentialCandidateSource struct {
	PhysicalDomain PhysicalDirectoryName        `json:"physical_domain" yaml:"physical_domain"`
	SourcePath     RepositoryRelativeSourcePath `json:"source_path" yaml:"source_path"`
	Document       MarkdownDocument             `json:"document" yaml:"document"`
}

// SequentialDomainRecordIndex Contains one sequential domain's uniquely addressable current-record references in both operation-defined ordering directions.
type SequentialDomainRecordIndex struct {
	AscendingRecordRefs  []CanonicalRecordReference `json:"ascending_record_refs" yaml:"ascending_record_refs"`
	DescendingRecordRefs []CanonicalRecordReference `json:"descending_record_refs" yaml:"descending_record_refs"`
}

func (SequentialDomainRecordIndex) isSequentialListingDomainSelectionOutcome() {}

// SequentialFormCandidateFunction References one resolved function satisfying the sequential current-record candidate-formation capability contract.
type SequentialFormCandidateFunction struct {
	value any
}

// SequentialFormCandidateOutcome Carries either one formed sequential candidate or the expected absence of a candidate for the supplied source.
type SequentialFormCandidateOutcome interface {
	isSequentialFormCandidateOutcome()
}

// SequentialListingAppSelectionOutcome Carries either the selected current app index or the shared unavailable-app context required to form an invalid-selector response.
type SequentialListingAppSelectionOutcome interface {
	isSequentialListingAppSelectionOutcome()
}

// SequentialListingArtifactSelectionOutcome Carries either the selected sequential artifact index or the shared unavailable-or-ineligible artifact context required to form an invalid-selector response.
type SequentialListingArtifactSelectionOutcome interface {
	isSequentialListingArtifactSelectionOutcome()
}

// SequentialListingDomainSelectionOutcome Carries either the selected sequential domain index or the shared unavailable-domain context required to form an invalid-selector response.
type SequentialListingDomainSelectionOutcome interface {
	isSequentialListingDomainSelectionOutcome()
}

// SequentialRecordListingItem Carries one listed canonical record reference and the three-state title and status projections required to distinguish omission, a projected value, and projected unavailability.
type SequentialRecordListingItem struct {
	CanonicalRef CanonicalRecordReference `json:"canonical_ref" yaml:"canonical_ref"`
	Title        **string                 `json:"title" yaml:"title"`
	Status       **string                 `json:"status" yaml:"status"`
}

// SequentialRecordListingOutcome Carries either one complete sequential record-listing result or one shared top-level operation error response.
type SequentialRecordListingOutcome interface {
	isSequentialRecordListingOutcome()
}

// SequentialRecordListingRequest Carries the schema-valid optional selectors, controls, and projection values accepted by sequential record listing before semantic validation and default application.
type SequentialRecordListingRequest struct {
	AppNamespace    *AppNamespace          `json:"app_namespace" yaml:"app_namespace"`
	ArtifactKind    *ArtifactKind          `json:"artifact_kind" yaml:"artifact_kind"`
	DomainNamespace *DomainNamespace       `json:"domain_namespace" yaml:"domain_namespace"`
	Order           *SequentialRecordOrder `json:"order" yaml:"order"`
	Limit           *int64                 `json:"limit" yaml:"limit"`
	Offset          *int64                 `json:"offset" yaml:"offset"`
	Projection      *[]string              `json:"projection" yaml:"projection"`
}

// SequentialRecordListingRequestValidationOutcome Carries either one fully validated and defaulted request or the first expected request-wide diagnostic context established by validation order.
type SequentialRecordListingRequestValidationOutcome interface {
	isSequentialRecordListingRequestValidationOutcome()
}

// SequentialRecordListingResult Carries one complete bounded sequential listing result after ordering, offset application, limit application, and requested field projection.
type SequentialRecordListingResult struct {
	Records       []SequentialRecordListingItem `json:"records" yaml:"records"`
	AppliedOffset int64                         `json:"applied_offset" yaml:"applied_offset"`
	AppliedLimit  int64                         `json:"applied_limit" yaml:"applied_limit"`
	HasMore       bool                          `json:"has_more" yaml:"has_more"`
}

func (SequentialRecordListingResult) isSequentialRecordListingOutcome() {}

// SequentialRecordOrder Identifies the closed ordering direction applied to one complete sequential ordering tuple.
type SequentialRecordOrder string

const (
	SequentialRecordOrderAscending  SequentialRecordOrder = "ascending"
	SequentialRecordOrderDescending SequentialRecordOrder = "descending"
)

// SequentialRecordOrderingKey Combines one sequential ordering tuple with the canonical-reference tie-break used for deterministic record ordering.
type SequentialRecordOrderingKey struct {
	Tuple        SequentialRecordOrderingTuple `json:"tuple" yaml:"tuple"`
	CanonicalRef CanonicalRecordReference      `json:"canonical_ref" yaml:"canonical_ref"`
}

// SequentialRecordOrderingTuple Carries the ordered integer values derived from sequence-bearing artifact-specific segments for one sequential record.
type SequentialRecordOrderingTuple struct {
	Values []int64 `json:"values" yaml:"values"`
}

// SequentialRecordProjectionSelection Carries the normalized set of optional record fields requested by one validated sequential listing request.
type SequentialRecordProjectionSelection struct {
	IncludeTitle  bool `json:"include_title" yaml:"include_title"`
	IncludeStatus bool `json:"include_status" yaml:"include_status"`
}

// SequentialReferenceDiscriminator Identifies the routing literal encoded in the artifact-kind position of one sequential canonical reference.
type SequentialReferenceDiscriminator string

// SequentialSegmentDeclaration Declares one artifact-specific sequential reference segment in canonical order and whether it contributes to record ordering.
type SequentialSegmentDeclaration struct {
	Name     SequentialSegmentName `json:"name" yaml:"name"`
	Sequence bool                  `json:"sequence" yaml:"sequence"`
}

// SequentialSegmentName Identifies one artifact-specific sequential reference segment declared by an artifact module.
type SequentialSegmentName string

// TerminalTreeNode Indicates that one selected current tree node has no direct current child nodes.
type TerminalTreeNode struct {
	NodeRef CanonicalRecordReference `json:"node_ref" yaml:"node_ref"`
}

func (TerminalTreeNode) isTreeChildListingOutcome() {}

// TreeArtifactCandidate Carries one tree artifact reference formed from one Markdown source under the selected artifact module contract.
type TreeArtifactCandidate struct {
	Reference TreeArtifactReference `json:"reference" yaml:"reference"`
}

func (TreeArtifactCandidate) isTreeFormCandidateOutcome() {}

// TreeArtifactModule Joins the manifest-derived declaration and bootstrap-resolved capabilities for one tree artifact kind.
type TreeArtifactModule struct {
	Declaration  TreeArtifactModuleDeclaration  `json:"declaration" yaml:"declaration"`
	Capabilities TreeArtifactModuleCapabilities `json:"capabilities" yaml:"capabilities"`
}

func (TreeArtifactModule) isArtifactModule() {}

// TreeArtifactModuleCapabilities Carries the bootstrap-resolved executable capabilities registered for one tree artifact kind.
type TreeArtifactModuleCapabilities struct {
	FormCandidate TreeFormCandidateFunction `json:"form_candidate" yaml:"form_candidate"`
}

// TreeArtifactModuleDeclaration Carries the manifest-derived identity, source-placement, and routing declarations for one tree artifact kind.
type TreeArtifactModuleDeclaration struct {
	ArtifactKind           ArtifactKind               `json:"artifact_kind" yaml:"artifact_kind"`
	ArtifactDirectory      ArtifactDirectory          `json:"artifact_directory" yaml:"artifact_directory"`
	ReferenceDiscriminator TreeReferenceDiscriminator `json:"reference_discriminator" yaml:"reference_discriminator"`
}

// TreeArtifactRecordIndex Contains one available tree artifact root and every current tree node addressable within that tree.
type TreeArtifactRecordIndex struct {
	RootRef CanonicalRecordReference                     `json:"root_ref" yaml:"root_ref"`
	Nodes   map[CanonicalRecordReference]CurrentTreeNode `json:"nodes" yaml:"nodes"`
}

func (TreeArtifactRecordIndex) isCurrentArtifactRecordIndex() {}

// TreeArtifactReference Carries one confirmed tree reference as its record-kind discriminator, app namespace, and ordered canonical path segments.
type TreeArtifactReference struct {
	RecordKind   TreeReferenceDiscriminator `json:"record_kind" yaml:"record_kind"`
	AppNamespace AppNamespace               `json:"app_namespace" yaml:"app_namespace"`
	PathSegments []TreeNodeSegment          `json:"path_segments" yaml:"path_segments"`
}

func (TreeArtifactReference) isArtifactReference() {}

// TreeArtifactSourceRootDiscovery Carries one tree artifact kind's source-root availability and physical tree together with the manifest-derived module declaration used to discover it.
type TreeArtifactSourceRootDiscovery struct {
	Declaration  TreeArtifactModuleDeclaration `json:"declaration" yaml:"declaration"`
	SourceRoot   ArtifactSourceRootPath        `json:"source_root" yaml:"source_root"`
	Available    bool                          `json:"available" yaml:"available"`
	PhysicalTree PhysicalDirectoryTree         `json:"physical_tree" yaml:"physical_tree"`
}

func (TreeArtifactSourceRootDiscovery) isArtifactRootSelectionOutcome() {}

func (TreeArtifactSourceRootDiscovery) isArtifactSourceRootDiscovery() {}

// TreeCandidateSource Carries one parsed Markdown source together with its artifact-relative tree path and repository-relative provenance.
type TreeCandidateSource struct {
	MarkdownPath ArtifactRelativeMarkdownPath `json:"markdown_path" yaml:"markdown_path"`
	SourcePath   RepositoryRelativeSourcePath `json:"source_path" yaml:"source_path"`
	Document     MarkdownDocument             `json:"document" yaml:"document"`
}

// TreeChildListingItem Carries one direct child segment, its current structural and record presence, and three-state title and status projections.
type TreeChildListingItem struct {
	Segment     TreeNodeSegment `json:"segment" yaml:"segment"`
	HasChildren bool            `json:"has_children" yaml:"has_children"`
	HasRecord   bool            `json:"has_record" yaml:"has_record"`
	Title       **string        `json:"title" yaml:"title"`
	Status      **string        `json:"status" yaml:"status"`
}

// TreeChildListingOutcome Carries one complete direct-child listing, one normal terminal-node result, or one shared top-level operation error response.
type TreeChildListingOutcome interface {
	isTreeChildListingOutcome()
}

// TreeChildListingRequest Carries one exact tree-node selector and the schema-valid optional controls and projection values accepted before semantic validation and default application.
type TreeChildListingRequest struct {
	NodeRef    CanonicalRecordReference `json:"node_ref" yaml:"node_ref"`
	Limit      *int64                   `json:"limit" yaml:"limit"`
	Offset     *int64                   `json:"offset" yaml:"offset"`
	Projection *[]string                `json:"projection" yaml:"projection"`
}

// TreeChildListingRequestValidationOutcome Carries either one fully validated and defaulted request or the first expected request-wide diagnostic context established by validation order.
type TreeChildListingRequestValidationOutcome interface {
	isTreeChildListingRequestValidationOutcome()
}

// TreeChildListingResult Carries one complete bounded direct-child listing after canonical sibling ordering, offset application, limit application, and requested field projection.
type TreeChildListingResult struct {
	NodeRef       CanonicalRecordReference `json:"node_ref" yaml:"node_ref"`
	Children      []TreeChildListingItem   `json:"children" yaml:"children"`
	AppliedOffset int64                    `json:"applied_offset" yaml:"applied_offset"`
	AppliedLimit  int64                    `json:"applied_limit" yaml:"applied_limit"`
	HasMore       bool                     `json:"has_more" yaml:"has_more"`
}

func (TreeChildListingResult) isTreeChildListingOutcome() {}

// TreeChildProjectionSelection Carries the normalized set of optional child-record fields requested by one validated tree child-listing request.
type TreeChildProjectionSelection struct {
	IncludeTitle  bool `json:"include_title" yaml:"include_title"`
	IncludeStatus bool `json:"include_status" yaml:"include_status"`
}

// TreeFormCandidateFunction References one resolved function satisfying the tree current-record candidate-formation capability contract.
type TreeFormCandidateFunction struct {
	value any
}

// TreeFormCandidateOutcome Carries either one formed tree candidate or the expected absence of a candidate for the supplied source.
type TreeFormCandidateOutcome interface {
	isTreeFormCandidateOutcome()
}

// TreeNodeNotFoundContext Carries one syntactically valid tree node reference that identifies no available current tree node.
type TreeNodeNotFoundContext struct {
	NodeRef CanonicalRecordReference `json:"node_ref" yaml:"node_ref"`
}

func (TreeNodeNotFoundContext) isCurrentTreeNodeSelectionOutcome() {}

func (TreeNodeNotFoundContext) isOperationDiagnosticContext() {}

// TreeNodeSegment Identifies one canonical tree identity segment relative to its parent current tree node.
type TreeNodeSegment string

// TreeOverviewNode Carries one structurally projected current tree node and every breadth-first-selected descendant rendered beneath it as a nested tree.
type TreeOverviewNode struct {
	Segment     TreeNodeSegment    `json:"segment" yaml:"segment"`
	HasChildren bool               `json:"has_children" yaml:"has_children"`
	Children    []TreeOverviewNode `json:"children" yaml:"children"`
}

// TreeOverviewOutcome Carries either one complete bounded tree overview or one shared top-level operation error response.
type TreeOverviewOutcome interface {
	isTreeOverviewOutcome()
}

// TreeOverviewRequest Carries one exact tree-node selector and the schema-valid optional depth and node-limit controls accepted before semantic validation and default application.
type TreeOverviewRequest struct {
	NodeRef   CanonicalRecordReference `json:"node_ref" yaml:"node_ref"`
	Depth     *int64                   `json:"depth" yaml:"depth"`
	NodeLimit *int64                   `json:"node_limit" yaml:"node_limit"`
}

// TreeOverviewRequestValidationOutcome Carries either one fully validated and defaulted request or the first expected request-wide diagnostic context established by validation order.
type TreeOverviewRequestValidationOutcome interface {
	isTreeOverviewRequestValidationOutcome()
}

// TreeOverviewResult Carries one bounded multi-level structural inspection rooted at the exact supplied current tree node and whether node-limit truncation occurred.
type TreeOverviewResult struct {
	NodeRef   CanonicalRecordReference `json:"node_ref" yaml:"node_ref"`
	Tree      TreeOverviewNode         `json:"tree" yaml:"tree"`
	Truncated bool                     `json:"truncated" yaml:"truncated"`
}

func (TreeOverviewResult) isTreeOverviewOutcome() {}

// TreeReferenceDiscriminator Identifies the routing literal encoded before the colon of one tree canonical reference.
type TreeReferenceDiscriminator string

// TreeRoot Carries the canonical root reference for one available tree artifact kind.
type TreeRoot struct {
	TreeRoot CanonicalRecordReference `json:"tree_root" yaml:"tree_root"`
}

func (TreeRoot) isRecordScopeDiscoveryOutcome() {}

// UnavailableAppNamespaceContext Carries one unavailable supplied app namespace and every currently available app namespace in canonical order.
type UnavailableAppNamespaceContext struct {
	AppNamespace           AppNamespace   `json:"app_namespace" yaml:"app_namespace"`
	AvailableAppNamespaces []AppNamespace `json:"available_app_namespaces" yaml:"available_app_namespaces"`
}

func (UnavailableAppNamespaceContext) isConfiguredAppSelectionOutcome() {}

func (UnavailableAppNamespaceContext) isOperationDiagnosticContext() {}

func (UnavailableAppNamespaceContext) isSequentialListingAppSelectionOutcome() {}

// UnavailableArtifactKindContext Carries one unavailable supplied artifact kind and every artifact kind available within the selected app in canonical order.
type UnavailableArtifactKindContext struct {
	ArtifactKind           ArtifactKind   `json:"artifact_kind" yaml:"artifact_kind"`
	AvailableArtifactKinds []ArtifactKind `json:"available_artifact_kinds" yaml:"available_artifact_kinds"`
}

func (UnavailableArtifactKindContext) isArtifactRootSelectionOutcome() {}

func (UnavailableArtifactKindContext) isOperationDiagnosticContext() {}

// UnavailableDomainNamespaceContext Carries one unavailable supplied sequential domain and every domain available within the selected app and artifact kind in canonical order.
type UnavailableDomainNamespaceContext struct {
	DomainNamespace           DomainNamespace   `json:"domain_namespace" yaml:"domain_namespace"`
	AvailableDomainNamespaces []DomainNamespace `json:"available_domain_namespaces" yaml:"available_domain_namespaces"`
}

func (UnavailableDomainNamespaceContext) isOperationDiagnosticContext() {}

func (UnavailableDomainNamespaceContext) isSequentialListingDomainSelectionOutcome() {}

// UnavailableSequentialArtifactKindContext Carries one unavailable or ineligible supplied artifact kind and every sequential artifact kind available within the selected app in canonical order.
type UnavailableSequentialArtifactKindContext struct {
	ArtifactKind                     ArtifactKind   `json:"artifact_kind" yaml:"artifact_kind"`
	AvailableSequentialArtifactKinds []ArtifactKind `json:"available_sequential_artifact_kinds" yaml:"available_sequential_artifact_kinds"`
}

func (UnavailableSequentialArtifactKindContext) isOperationDiagnosticContext() {}

func (UnavailableSequentialArtifactKindContext) isSequentialListingArtifactSelectionOutcome() {}

// ValidatedSequentialRecordListingRequest Carries every required selector and every defaulted control needed to select and execute one sequential domain listing.
type ValidatedSequentialRecordListingRequest struct {
	AppNamespace    AppNamespace                        `json:"app_namespace" yaml:"app_namespace"`
	ArtifactKind    ArtifactKind                        `json:"artifact_kind" yaml:"artifact_kind"`
	DomainNamespace DomainNamespace                     `json:"domain_namespace" yaml:"domain_namespace"`
	Order           SequentialRecordOrder               `json:"order" yaml:"order"`
	Limit           int64                               `json:"limit" yaml:"limit"`
	Offset          int64                               `json:"offset" yaml:"offset"`
	Projection      SequentialRecordProjectionSelection `json:"projection" yaml:"projection"`
}

func (ValidatedSequentialRecordListingRequest) isSequentialRecordListingRequestValidationOutcome() {}

// ValidatedTreeChildListingRequest Carries one confirmed tree-node selector, its extracted current-scope selectors, and every defaulted control needed to execute direct-child listing.
type ValidatedTreeChildListingRequest struct {
	NodeRef      CanonicalRecordReference     `json:"node_ref" yaml:"node_ref"`
	AppNamespace AppNamespace                 `json:"app_namespace" yaml:"app_namespace"`
	ArtifactKind ArtifactKind                 `json:"artifact_kind" yaml:"artifact_kind"`
	Limit        int64                        `json:"limit" yaml:"limit"`
	Offset       int64                        `json:"offset" yaml:"offset"`
	Projection   TreeChildProjectionSelection `json:"projection" yaml:"projection"`
}

func (ValidatedTreeChildListingRequest) isTreeChildListingRequestValidationOutcome() {}

// ValidatedTreeOverviewRequest Carries one confirmed tree-node selector, its extracted current-scope selectors, and every defaulted traversal control needed to inspect one bounded subtree.
type ValidatedTreeOverviewRequest struct {
	NodeRef      CanonicalRecordReference `json:"node_ref" yaml:"node_ref"`
	AppNamespace AppNamespace             `json:"app_namespace" yaml:"app_namespace"`
	ArtifactKind ArtifactKind             `json:"artifact_kind" yaml:"artifact_kind"`
	Depth        int64                    `json:"depth" yaml:"depth"`
	NodeLimit    int64                    `json:"node_limit" yaml:"node_limit"`
}

func (ValidatedTreeOverviewRequest) isTreeOverviewRequestValidationOutcome() {}
