// Code generated by PuppyDSL. DO NOT EDIT.

package sequential_ordering

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var buildDomainRecordIndexFunction = native.Function{
	ID:        "artifact.base.sequential_ordering._build_domain_record_index",
	Signature: "( declarations: list<SequentialSegmentDeclaration>, records: list<CurrentRecord> ) -> SequentialDomainRecordIndex",
}

// BuildDomainRecordIndex Builds both deterministic ordering directions for uniquely addressable records within one sequential domain by tuple order and canonical-reference tie-break.
func BuildDomainRecordIndex(call native.Call, declarations []types.SequentialSegmentDeclaration, records []types.CurrentRecord) (types.SequentialDomainRecordIndex, error) {
	value, err := call.Invoke(buildDomainRecordIndexFunction, []any{declarations, records})
	if err != nil {
		var zero types.SequentialDomainRecordIndex
		return zero, err
	}
	return native.Output[types.SequentialDomainRecordIndex](buildDomainRecordIndexFunction, value)
}

var deriveTupleFunction = native.Function{
	ID:        "artifact.base.sequential_ordering._derive_tuple",
	Signature: "( declarations: list<SequentialSegmentDeclaration>, reference: SequentialArtifactReference ) -> SequentialRecordOrderingTuple",
}

// DeriveTuple Derives one ordering tuple by reading sequence-bearing segment values from a confirmed sequential reference in module declaration order.
func DeriveTuple(call native.Call, declarations []types.SequentialSegmentDeclaration, reference types.SequentialArtifactReference) (types.SequentialRecordOrderingTuple, error) {
	value, err := call.Invoke(deriveTupleFunction, []any{declarations, reference})
	if err != nil {
		var zero types.SequentialRecordOrderingTuple
		return zero, err
	}
	return native.Output[types.SequentialRecordOrderingTuple](deriveTupleFunction, value)
}
