// Code generated by PuppyDSL. DO NOT EDIT.

package discovery_and_listing

import (
	types "github.com/hiroshiasayadev-prog/brewprint/drmcp/puppydsl/go_native/puppygen/types"
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var asRecordScopeDiscoveryOutcomeFunction = native.Function{
	ID:        "operation.discovery_and_listing._as_record_scope_discovery_outcome",
	Signature: "( outcome: RecordScopeDiscoveryOutcome ) -> RecordScopeDiscoveryOutcome",
}

// AsRecordScopeDiscoveryOutcome Preserves one concrete record-scope success result or shared top-level error response as the operation outcome union.
func AsRecordScopeDiscoveryOutcome(call native.Call, outcome types.RecordScopeDiscoveryOutcome) (types.RecordScopeDiscoveryOutcome, error) {
	value, err := call.Invoke(asRecordScopeDiscoveryOutcomeFunction, []any{outcome})
	if err != nil {
		var zero types.RecordScopeDiscoveryOutcome
		return zero, err
	}
	return native.Output[types.RecordScopeDiscoveryOutcome](asRecordScopeDiscoveryOutcomeFunction, value)
}

var asSequentialRecordListingOutcomeFunction = native.Function{
	ID:        "operation.discovery_and_listing._as_sequential_record_listing_outcome",
	Signature: "( outcome: SequentialRecordListingOutcome ) -> SequentialRecordListingOutcome",
}

// AsSequentialRecordListingOutcome Preserves one complete sequential listing result or shared top-level error response as the operation outcome union.
func AsSequentialRecordListingOutcome(call native.Call, outcome types.SequentialRecordListingOutcome) (types.SequentialRecordListingOutcome, error) {
	value, err := call.Invoke(asSequentialRecordListingOutcomeFunction, []any{outcome})
	if err != nil {
		var zero types.SequentialRecordListingOutcome
		return zero, err
	}
	return native.Output[types.SequentialRecordListingOutcome](asSequentialRecordListingOutcomeFunction, value)
}

var asTreeChildListingOutcomeFunction = native.Function{
	ID:        "operation.discovery_and_listing._as_tree_child_listing_outcome",
	Signature: "( outcome: TreeChildListingOutcome ) -> TreeChildListingOutcome",
}

// AsTreeChildListingOutcome Preserves one complete child-listing result, normal terminal-node result, or shared top-level error response as the operation outcome union.
func AsTreeChildListingOutcome(call native.Call, outcome types.TreeChildListingOutcome) (types.TreeChildListingOutcome, error) {
	value, err := call.Invoke(asTreeChildListingOutcomeFunction, []any{outcome})
	if err != nil {
		var zero types.TreeChildListingOutcome
		return zero, err
	}
	return native.Output[types.TreeChildListingOutcome](asTreeChildListingOutcomeFunction, value)
}

var asTreeOverviewOutcomeFunction = native.Function{
	ID:        "operation.discovery_and_listing._as_tree_overview_outcome",
	Signature: "( outcome: TreeOverviewOutcome ) -> TreeOverviewOutcome",
}

// AsTreeOverviewOutcome Preserves one complete bounded tree-overview result or shared top-level error response as the operation outcome union.
func AsTreeOverviewOutcome(call native.Call, outcome types.TreeOverviewOutcome) (types.TreeOverviewOutcome, error) {
	value, err := call.Invoke(asTreeOverviewOutcomeFunction, []any{outcome})
	if err != nil {
		var zero types.TreeOverviewOutcome
		return zero, err
	}
	return native.Output[types.TreeOverviewOutcome](asTreeOverviewOutcomeFunction, value)
}

var buildSequentialRecordListingResultFunction = native.Function{
	ID:        "operation.discovery_and_listing._build_sequential_record_listing_result",
	Signature: "( records: dict<CanonicalRecordReference, CurrentRecord>, ordered_record_refs: list<CanonicalRecordReference>, offset: integer, limit: integer, projection: SequentialRecordProjectionSelection ) -> SequentialRecordListingResult",
}

// BuildSequentialRecordListingResult Applies offset and limit to one ordered domain reference list, resolves retained records, projects requested title and status fields, and computes the complete range indicators.
func BuildSequentialRecordListingResult(call native.Call, records map[types.CanonicalRecordReference]types.CurrentRecord, orderedRecordRefs []types.CanonicalRecordReference, offset int64, limit int64, projection types.SequentialRecordProjectionSelection) (types.SequentialRecordListingResult, error) {
	value, err := call.Invoke(buildSequentialRecordListingResultFunction, []any{records, orderedRecordRefs, offset, limit, projection})
	if err != nil {
		var zero types.SequentialRecordListingResult
		return zero, err
	}
	return native.Output[types.SequentialRecordListingResult](buildSequentialRecordListingResultFunction, value)
}

var buildTreeChildListingResultFunction = native.Function{
	ID:        "operation.discovery_and_listing._build_tree_child_listing_result",
	Signature: "( node_ref: CanonicalRecordReference, selected: SelectedCurrentTreeNode, records: dict<CanonicalRecordReference, CurrentRecord>, offset: integer, limit: integer, projection: TreeChildProjectionSelection ) -> TreeChildListingResult",
}

// BuildTreeChildListingResult Orders direct children by canonical segment, applies offset and limit, resolves structural and record presence, projects requested title and status fields, and computes complete range indicators.
func BuildTreeChildListingResult(call native.Call, nodeRef types.CanonicalRecordReference, selected types.SelectedCurrentTreeNode, records map[types.CanonicalRecordReference]types.CurrentRecord, offset int64, limit int64, projection types.TreeChildProjectionSelection) (types.TreeChildListingResult, error) {
	value, err := call.Invoke(buildTreeChildListingResultFunction, []any{nodeRef, selected, records, offset, limit, projection})
	if err != nil {
		var zero types.TreeChildListingResult
		return zero, err
	}
	return native.Output[types.TreeChildListingResult](buildTreeChildListingResultFunction, value)
}

var buildTreeOverviewResultFunction = native.Function{
	ID:        "operation.discovery_and_listing._build_tree_overview_result",
	Signature: "( node_ref: CanonicalRecordReference, selected: SelectedCurrentTreeNode, depth: integer, node_limit: integer ) -> TreeOverviewResult",
}

// BuildTreeOverviewResult Selects current tree nodes through breadth-first traversal within the requested depth and node limit, renders the selected nodes as a nested structural tree, and reports node-limit truncation.
func BuildTreeOverviewResult(call native.Call, nodeRef types.CanonicalRecordReference, selected types.SelectedCurrentTreeNode, depth int64, nodeLimit int64) (types.TreeOverviewResult, error) {
	value, err := call.Invoke(buildTreeOverviewResultFunction, []any{nodeRef, selected, depth, nodeLimit})
	if err != nil {
		var zero types.TreeOverviewResult
		return zero, err
	}
	return native.Output[types.TreeOverviewResult](buildTreeOverviewResultFunction, value)
}

var discoverAppScopesFunction = native.Function{
	ID:        "operation.discovery_and_listing._discover_app_scopes",
	Signature: "( inventory: RepositoryDiscoveryInventory ) -> AppScopes",
}

// DiscoverAppScopes Projects every configured app in canonical app-namespace key order without exposing physical paths.
func DiscoverAppScopes(call native.Call, inventory types.RepositoryDiscoveryInventory) (types.AppScopes, error) {
	value, err := call.Invoke(discoverAppScopesFunction, []any{inventory})
	if err != nil {
		var zero types.AppScopes
		return zero, err
	}
	return native.Output[types.AppScopes](discoverAppScopesFunction, value)
}

var discoverArtifactKindScopesFunction = native.Function{
	ID:        "operation.discovery_and_listing._discover_artifact_kind_scopes",
	Signature: "( app: ConfiguredAppDiscovery ) -> ArtifactKindScopes",
}

// DiscoverArtifactKindScopes Projects every available artifact kind and its declared structure in canonical artifact-kind key order.
func DiscoverArtifactKindScopes(call native.Call, app types.ConfiguredAppDiscovery) (types.ArtifactKindScopes, error) {
	value, err := call.Invoke(discoverArtifactKindScopesFunction, []any{app})
	if err != nil {
		var zero types.ArtifactKindScopes
		return zero, err
	}
	return native.Output[types.ArtifactKindScopes](discoverArtifactKindScopesFunction, value)
}

var discoverDomainScopesFunction = native.Function{
	ID:        "operation.discovery_and_listing._discover_domain_scopes",
	Signature: "( artifact_root: SequentialArtifactSourceRootDiscovery ) -> DomainScopes",
}

// DiscoverDomainScopes Projects direct physical domain directories containing at least one direct Markdown source into canonical domain-namespace order without exposing physical paths.
func DiscoverDomainScopes(call native.Call, artifactRoot types.SequentialArtifactSourceRootDiscovery) (types.DomainScopes, error) {
	value, err := call.Invoke(discoverDomainScopesFunction, []any{artifactRoot})
	if err != nil {
		var zero types.DomainScopes
		return zero, err
	}
	return native.Output[types.DomainScopes](discoverDomainScopesFunction, value)
}

var discoverTreeRootFunction = native.Function{
	ID:        "operation.discovery_and_listing._discover_tree_root",
	Signature: "( app_namespace: AppNamespace, artifact_root: TreeArtifactSourceRootDiscovery ) -> TreeRoot",
}

// DiscoverTreeRoot Produces the canonical root reference for one selected tree artifact kind and configured app namespace.
func DiscoverTreeRoot(call native.Call, appNamespace types.AppNamespace, artifactRoot types.TreeArtifactSourceRootDiscovery) (types.TreeRoot, error) {
	value, err := call.Invoke(discoverTreeRootFunction, []any{appNamespace, artifactRoot})
	if err != nil {
		var zero types.TreeRoot
		return zero, err
	}
	return native.Output[types.TreeRoot](discoverTreeRootFunction, value)
}

var formCurrentTreeNodeNotFoundErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_current_tree_node_not_found_error",
	Signature: "( context: TreeNodeNotFoundContext ) -> OperationErrorResponse",
}

// FormCurrentTreeNodeNotFoundError Forms the shared top-level node-not-found response for one syntactically valid tree selector that identifies no available current tree node.
func FormCurrentTreeNodeNotFoundError(call native.Call, context types.TreeNodeNotFoundContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formCurrentTreeNodeNotFoundErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formCurrentTreeNodeNotFoundErrorFunction, value)
}

var formInvalidSelectorCombinationErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_selector_combination_error",
	Signature: "( context: AcceptedSelectorCombinationsContext ) -> OperationErrorResponse",
}

// FormInvalidSelectorCombinationError Forms the shared top-level invalid-selector response for one unsupported record-scope selector combination.
func FormInvalidSelectorCombinationError(call native.Call, context types.AcceptedSelectorCombinationsContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidSelectorCombinationErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidSelectorCombinationErrorFunction, value)
}

var formInvalidSequentialListingLimitErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_sequential_listing_limit_error",
	Signature: "( context: BoundedIntegerContext ) -> OperationErrorResponse",
}

// FormInvalidSequentialListingLimitError Forms the shared top-level invalid-limit response for a sequential-listing limit outside the accepted inclusive bounds.
func FormInvalidSequentialListingLimitError(call native.Call, context types.BoundedIntegerContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidSequentialListingLimitErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidSequentialListingLimitErrorFunction, value)
}

var formInvalidSequentialListingOffsetErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_sequential_listing_offset_error",
	Signature: "( context: MinimumIntegerContext ) -> OperationErrorResponse",
}

// FormInvalidSequentialListingOffsetError Forms the shared top-level invalid-offset response for a negative sequential-listing offset.
func FormInvalidSequentialListingOffsetError(call native.Call, context types.MinimumIntegerContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidSequentialListingOffsetErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidSequentialListingOffsetErrorFunction, value)
}

var formInvalidSequentialListingProjectionErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_sequential_listing_projection_error",
	Signature: "( context: InvalidProjectionContext ) -> OperationErrorResponse",
}

// FormInvalidSequentialListingProjectionError Forms the shared top-level invalid-projection response for unknown sequential-listing projection values.
func FormInvalidSequentialListingProjectionError(call native.Call, context types.InvalidProjectionContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidSequentialListingProjectionErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidSequentialListingProjectionErrorFunction, value)
}

var formInvalidTreeChildLimitErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_tree_child_limit_error",
	Signature: "( context: BoundedIntegerContext ) -> OperationErrorResponse",
}

// FormInvalidTreeChildLimitError Forms the shared top-level invalid-limit response for a tree child-listing limit outside the accepted inclusive bounds.
func FormInvalidTreeChildLimitError(call native.Call, context types.BoundedIntegerContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidTreeChildLimitErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidTreeChildLimitErrorFunction, value)
}

var formInvalidTreeChildOffsetErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_tree_child_offset_error",
	Signature: "( context: MinimumIntegerContext ) -> OperationErrorResponse",
}

// FormInvalidTreeChildOffsetError Forms the shared top-level invalid-offset response for a negative tree child-listing offset.
func FormInvalidTreeChildOffsetError(call native.Call, context types.MinimumIntegerContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidTreeChildOffsetErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidTreeChildOffsetErrorFunction, value)
}

var formInvalidTreeChildProjectionErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_tree_child_projection_error",
	Signature: "( context: InvalidProjectionContext ) -> OperationErrorResponse",
}

// FormInvalidTreeChildProjectionError Forms the shared top-level invalid-projection response for unknown tree child-listing projection values.
func FormInvalidTreeChildProjectionError(call native.Call, context types.InvalidProjectionContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidTreeChildProjectionErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidTreeChildProjectionErrorFunction, value)
}

var formInvalidTreeNodeSelectorErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_tree_node_selector_error",
	Signature: "( context: InvalidTreeNodeSelectorContext ) -> OperationErrorResponse",
}

// FormInvalidTreeNodeSelectorError Forms the shared top-level invalid-selector response for a malformed node reference or one that does not identify a registered tree artifact kind.
func FormInvalidTreeNodeSelectorError(call native.Call, context types.InvalidTreeNodeSelectorContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidTreeNodeSelectorErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidTreeNodeSelectorErrorFunction, value)
}

var formInvalidTreeOverviewDepthErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_tree_overview_depth_error",
	Signature: "( invalid: InvalidTreeOverviewDepth ) -> OperationErrorResponse",
}

// FormInvalidTreeOverviewDepthError Forms the shared top-level invalid-depth response for a tree-overview depth outside the accepted inclusive bounds.
func FormInvalidTreeOverviewDepthError(call native.Call, invalid types.InvalidTreeOverviewDepth) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidTreeOverviewDepthErrorFunction, []any{invalid})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidTreeOverviewDepthErrorFunction, value)
}

var formInvalidTreeOverviewNodeLimitErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_invalid_tree_overview_node_limit_error",
	Signature: "( invalid: InvalidTreeOverviewNodeLimit ) -> OperationErrorResponse",
}

// FormInvalidTreeOverviewNodeLimitError Forms the shared top-level invalid-node-limit response for a tree-overview node limit outside the accepted inclusive bounds.
func FormInvalidTreeOverviewNodeLimitError(call native.Call, invalid types.InvalidTreeOverviewNodeLimit) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formInvalidTreeOverviewNodeLimitErrorFunction, []any{invalid})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formInvalidTreeOverviewNodeLimitErrorFunction, value)
}

var formMissingSequentialListingSelectorErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_missing_sequential_listing_selector_error",
	Signature: "( context: MissingSelectorFieldsContext ) -> OperationErrorResponse",
}

// FormMissingSequentialListingSelectorError Forms the shared top-level invalid-selector response for omitted required sequential-listing selectors.
func FormMissingSequentialListingSelectorError(call native.Call, context types.MissingSelectorFieldsContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formMissingSequentialListingSelectorErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formMissingSequentialListingSelectorErrorFunction, value)
}

var formTerminalTreeNodeFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_terminal_tree_node",
	Signature: "( node_ref: CanonicalRecordReference ) -> TerminalTreeNode",
}

// FormTerminalTreeNode Forms the normal terminal-node result for one selected current tree node with no direct current children.
func FormTerminalTreeNode(call native.Call, nodeRef types.CanonicalRecordReference) (types.TerminalTreeNode, error) {
	value, err := call.Invoke(formTerminalTreeNodeFunction, []any{nodeRef})
	if err != nil {
		var zero types.TerminalTreeNode
		return zero, err
	}
	return native.Output[types.TerminalTreeNode](formTerminalTreeNodeFunction, value)
}

var formUnavailableAppNamespaceErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_unavailable_app_namespace_error",
	Signature: "( context: UnavailableAppNamespaceContext ) -> OperationErrorResponse",
}

// FormUnavailableAppNamespaceError Forms the shared top-level invalid-selector response for one unavailable app namespace.
func FormUnavailableAppNamespaceError(call native.Call, context types.UnavailableAppNamespaceContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formUnavailableAppNamespaceErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formUnavailableAppNamespaceErrorFunction, value)
}

var formUnavailableArtifactKindErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_unavailable_artifact_kind_error",
	Signature: "( context: UnavailableArtifactKindContext ) -> OperationErrorResponse",
}

// FormUnavailableArtifactKindError Forms the shared top-level invalid-selector response for one artifact kind unavailable within the selected app.
func FormUnavailableArtifactKindError(call native.Call, context types.UnavailableArtifactKindContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formUnavailableArtifactKindErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formUnavailableArtifactKindErrorFunction, value)
}

var formUnavailableDomainNamespaceErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_unavailable_domain_namespace_error",
	Signature: "( context: UnavailableDomainNamespaceContext ) -> OperationErrorResponse",
}

// FormUnavailableDomainNamespaceError Forms the shared top-level invalid-selector response for an unavailable sequential domain namespace.
func FormUnavailableDomainNamespaceError(call native.Call, context types.UnavailableDomainNamespaceContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formUnavailableDomainNamespaceErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formUnavailableDomainNamespaceErrorFunction, value)
}

var formUnavailableSequentialArtifactKindErrorFunction = native.Function{
	ID:        "operation.discovery_and_listing._form_unavailable_sequential_artifact_kind_error",
	Signature: "( context: UnavailableSequentialArtifactKindContext ) -> OperationErrorResponse",
}

// FormUnavailableSequentialArtifactKindError Forms the shared top-level invalid-selector response for an unavailable or ineligible sequential artifact kind.
func FormUnavailableSequentialArtifactKindError(call native.Call, context types.UnavailableSequentialArtifactKindContext) (types.OperationErrorResponse, error) {
	value, err := call.Invoke(formUnavailableSequentialArtifactKindErrorFunction, []any{context})
	if err != nil {
		var zero types.OperationErrorResponse
		return zero, err
	}
	return native.Output[types.OperationErrorResponse](formUnavailableSequentialArtifactKindErrorFunction, value)
}

var handleAppScopesRouteFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_app_scopes_route",
	Signature: "() -> RecordScopeDiscoveryOutcome",
}

// HandleAppScopesRoute Produces the app-scope outcome selected when neither request selector is supplied.
func HandleAppScopesRoute(call native.Call) (types.RecordScopeDiscoveryOutcome, error) {
	value, err := call.Invoke(handleAppScopesRouteFunction, nil)
	if err != nil {
		var zero types.RecordScopeDiscoveryOutcome
		return zero, err
	}
	return native.Output[types.RecordScopeDiscoveryOutcome](handleAppScopesRouteFunction, value)
}

var handleArtifactKindScopesRouteFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_artifact_kind_scopes_route",
	Signature: "( route: ArtifactKindScopesRoute ) -> RecordScopeDiscoveryOutcome",
}

// HandleArtifactKindScopesRoute Selects one configured app and produces either its available artifact-kind scopes or the shared unavailable-app error response.
func HandleArtifactKindScopesRoute(call native.Call, route types.ArtifactKindScopesRoute) (types.RecordScopeDiscoveryOutcome, error) {
	value, err := call.Invoke(handleArtifactKindScopesRouteFunction, []any{route})
	if err != nil {
		var zero types.RecordScopeDiscoveryOutcome
		return zero, err
	}
	return native.Output[types.RecordScopeDiscoveryOutcome](handleArtifactKindScopesRouteFunction, value)
}

var handleArtifactScopeRouteFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_artifact_scope_route",
	Signature: "( route: ArtifactScopeRoute ) -> RecordScopeDiscoveryOutcome",
}

// HandleArtifactScopeRoute Selects one configured app and artifact kind, then produces sequential domain scopes, a tree root, or the corresponding shared invalid-selector error response.
func HandleArtifactScopeRoute(call native.Call, route types.ArtifactScopeRoute) (types.RecordScopeDiscoveryOutcome, error) {
	value, err := call.Invoke(handleArtifactScopeRouteFunction, []any{route})
	if err != nil {
		var zero types.RecordScopeDiscoveryOutcome
		return zero, err
	}
	return native.Output[types.RecordScopeDiscoveryOutcome](handleArtifactScopeRouteFunction, value)
}

var handleInvalidSelectorCombinationFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_invalid_selector_combination",
	Signature: "( context: AcceptedSelectorCombinationsContext ) -> RecordScopeDiscoveryOutcome",
}

// HandleInvalidSelectorCombination Converts the accepted-selector-combinations context selected by request routing into the shared top-level invalid-selector response.
func HandleInvalidSelectorCombination(call native.Call, context types.AcceptedSelectorCombinationsContext) (types.RecordScopeDiscoveryOutcome, error) {
	value, err := call.Invoke(handleInvalidSelectorCombinationFunction, []any{context})
	if err != nil {
		var zero types.RecordScopeDiscoveryOutcome
		return zero, err
	}
	return native.Output[types.RecordScopeDiscoveryOutcome](handleInvalidSelectorCombinationFunction, value)
}

var handleSelectedTreeChildListingNodeFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_selected_tree_child_listing_node",
	Signature: "( request: ValidatedTreeChildListingRequest, selected: SelectedCurrentTreeNode ) -> TreeChildListingOutcome",
}

// HandleSelectedTreeChildListingNode Produces the normal terminal-node outcome or the complete bounded direct-child listing for one selected current tree node.
func HandleSelectedTreeChildListingNode(call native.Call, request types.ValidatedTreeChildListingRequest, selected types.SelectedCurrentTreeNode) (types.TreeChildListingOutcome, error) {
	value, err := call.Invoke(handleSelectedTreeChildListingNodeFunction, []any{request, selected})
	if err != nil {
		var zero types.TreeChildListingOutcome
		return zero, err
	}
	return native.Output[types.TreeChildListingOutcome](handleSelectedTreeChildListingNodeFunction, value)
}

var handleValidatedSequentialRecordListingFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_validated_sequential_record_listing",
	Signature: "( request: ValidatedSequentialRecordListingRequest ) -> SequentialRecordListingOutcome",
}

// HandleValidatedSequentialRecordListing Selects one current sequential domain, chooses its precomputed ordering, and builds the complete bounded projected listing or the first current-state selector error.
func HandleValidatedSequentialRecordListing(call native.Call, request types.ValidatedSequentialRecordListingRequest) (types.SequentialRecordListingOutcome, error) {
	value, err := call.Invoke(handleValidatedSequentialRecordListingFunction, []any{request})
	if err != nil {
		var zero types.SequentialRecordListingOutcome
		return zero, err
	}
	return native.Output[types.SequentialRecordListingOutcome](handleValidatedSequentialRecordListingFunction, value)
}

var handleValidatedTreeChildListingFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_validated_tree_child_listing",
	Signature: "( request: ValidatedTreeChildListingRequest ) -> TreeChildListingOutcome",
}

// HandleValidatedTreeChildListing Selects one exact current tree node and produces its terminal or bounded direct-child result, or the shared node-not-found response.
func HandleValidatedTreeChildListing(call native.Call, request types.ValidatedTreeChildListingRequest) (types.TreeChildListingOutcome, error) {
	value, err := call.Invoke(handleValidatedTreeChildListingFunction, []any{request})
	if err != nil {
		var zero types.TreeChildListingOutcome
		return zero, err
	}
	return native.Output[types.TreeChildListingOutcome](handleValidatedTreeChildListingFunction, value)
}

var handleValidatedTreeOverviewFunction = native.Function{
	ID:        "operation.discovery_and_listing._handle_validated_tree_overview",
	Signature: "( request: ValidatedTreeOverviewRequest ) -> TreeOverviewOutcome",
}

// HandleValidatedTreeOverview Selects one exact current tree node and builds its bounded breadth-first structural overview or returns the shared node-not-found response.
func HandleValidatedTreeOverview(call native.Call, request types.ValidatedTreeOverviewRequest) (types.TreeOverviewOutcome, error) {
	value, err := call.Invoke(handleValidatedTreeOverviewFunction, []any{request})
	if err != nil {
		var zero types.TreeOverviewOutcome
		return zero, err
	}
	return native.Output[types.TreeOverviewOutcome](handleValidatedTreeOverviewFunction, value)
}

var hasDirectTreeChildrenFunction = native.Function{
	ID:        "operation.discovery_and_listing._has_direct_tree_children",
	Signature: "( node: CurrentTreeNode ) -> boolean",
}

// HasDirectTreeChildren Reports whether one selected current tree node has at least one direct current child before range application.
func HasDirectTreeChildren(call native.Call, node types.CurrentTreeNode) (bool, error) {
	value, err := call.Invoke(hasDirectTreeChildrenFunction, []any{node})
	if err != nil {
		var zero bool
		return zero, err
	}
	return native.Output[bool](hasDirectTreeChildrenFunction, value)
}

var routeRecordScopeSelectorFunction = native.Function{
	ID:        "operation.discovery_and_listing._route_record_scope_selector",
	Signature: "( request: RecordScopeDiscoveryRequest ) -> RecordScopeDiscoverySelectorRoute",
}

// RouteRecordScopeSelector Derives one typed record-scope route or the accepted selector-field combinations required to diagnose an unsupported request combination.
func RouteRecordScopeSelector(call native.Call, request types.RecordScopeDiscoveryRequest) (types.RecordScopeDiscoverySelectorRoute, error) {
	value, err := call.Invoke(routeRecordScopeSelectorFunction, []any{request})
	if err != nil {
		var zero types.RecordScopeDiscoverySelectorRoute
		return zero, err
	}
	return native.Output[types.RecordScopeDiscoverySelectorRoute](routeRecordScopeSelectorFunction, value)
}

var selectArtifactRootFunction = native.Function{
	ID:        "operation.discovery_and_listing._select_artifact_root",
	Signature: "( app: ConfiguredAppDiscovery, artifact_kind: ArtifactKind ) -> ArtifactRootSelectionOutcome",
}

// SelectArtifactRoot Selects one available artifact source root from the configured app's keyed inventory or returns the shared unavailable-kind context.
func SelectArtifactRoot(call native.Call, app types.ConfiguredAppDiscovery, artifactKind types.ArtifactKind) (types.ArtifactRootSelectionOutcome, error) {
	value, err := call.Invoke(selectArtifactRootFunction, []any{app, artifactKind})
	if err != nil {
		var zero types.ArtifactRootSelectionOutcome
		return zero, err
	}
	return native.Output[types.ArtifactRootSelectionOutcome](selectArtifactRootFunction, value)
}

var selectConfiguredAppFunction = native.Function{
	ID:        "operation.discovery_and_listing._select_configured_app",
	Signature: "( inventory: RepositoryDiscoveryInventory, app_namespace: AppNamespace ) -> ConfiguredAppSelectionOutcome",
}

// SelectConfiguredApp Selects one configured app from the keyed repository inventory or returns the shared unavailable-app context.
func SelectConfiguredApp(call native.Call, inventory types.RepositoryDiscoveryInventory, appNamespace types.AppNamespace) (types.ConfiguredAppSelectionOutcome, error) {
	value, err := call.Invoke(selectConfiguredAppFunction, []any{inventory, appNamespace})
	if err != nil {
		var zero types.ConfiguredAppSelectionOutcome
		return zero, err
	}
	return native.Output[types.ConfiguredAppSelectionOutcome](selectConfiguredAppFunction, value)
}

var selectCurrentTreeNodeFunction = native.Function{
	ID:        "operation.discovery_and_listing._select_current_tree_node",
	Signature: "( state: CurrentRecordState, node_ref: CanonicalRecordReference, app_namespace: AppNamespace, artifact_kind: ArtifactKind ) -> CurrentTreeNodeSelectionOutcome",
}

// SelectCurrentTreeNode Selects one exact current tree index and node from validated app, artifact-kind, and canonical-reference selectors or returns the shared node-not-found context without exposing failed intermediate scope detail.
func SelectCurrentTreeNode(call native.Call, state types.CurrentRecordState, nodeRef types.CanonicalRecordReference, appNamespace types.AppNamespace, artifactKind types.ArtifactKind) (types.CurrentTreeNodeSelectionOutcome, error) {
	value, err := call.Invoke(selectCurrentTreeNodeFunction, []any{state, nodeRef, appNamespace, artifactKind})
	if err != nil {
		var zero types.CurrentTreeNodeSelectionOutcome
		return zero, err
	}
	return native.Output[types.CurrentTreeNodeSelectionOutcome](selectCurrentTreeNodeFunction, value)
}

var selectOrderedSequentialRecordRefsFunction = native.Function{
	ID:        "operation.discovery_and_listing._select_ordered_sequential_record_refs",
	Signature: "( domain: SequentialDomainRecordIndex, order: SequentialRecordOrder ) -> list<CanonicalRecordReference>",
}

// SelectOrderedSequentialRecordRefs Selects the precomputed deterministic canonical-reference ordering requested for one sequential domain without recomputing ordering tuples.
func SelectOrderedSequentialRecordRefs(call native.Call, domain types.SequentialDomainRecordIndex, order types.SequentialRecordOrder) ([]types.CanonicalRecordReference, error) {
	value, err := call.Invoke(selectOrderedSequentialRecordRefsFunction, []any{domain, order})
	if err != nil {
		var zero []types.CanonicalRecordReference
		return zero, err
	}
	return native.Output[[]types.CanonicalRecordReference](selectOrderedSequentialRecordRefsFunction, value)
}

var selectSequentialListingAppFunction = native.Function{
	ID:        "operation.discovery_and_listing._select_sequential_listing_app",
	Signature: "( state: CurrentRecordState, app_namespace: AppNamespace ) -> SequentialListingAppSelectionOutcome",
}

// SelectSequentialListingApp Selects one current app index or returns the shared unavailable-app context with every available app namespace in canonical order.
func SelectSequentialListingApp(call native.Call, state types.CurrentRecordState, appNamespace types.AppNamespace) (types.SequentialListingAppSelectionOutcome, error) {
	value, err := call.Invoke(selectSequentialListingAppFunction, []any{state, appNamespace})
	if err != nil {
		var zero types.SequentialListingAppSelectionOutcome
		return zero, err
	}
	return native.Output[types.SequentialListingAppSelectionOutcome](selectSequentialListingAppFunction, value)
}

var selectSequentialListingArtifactFunction = native.Function{
	ID:        "operation.discovery_and_listing._select_sequential_listing_artifact",
	Signature: "( app: CurrentAppRecordIndex, artifact_kind: ArtifactKind ) -> SequentialListingArtifactSelectionOutcome",
}

// SelectSequentialListingArtifact Selects one available sequential artifact index or returns the shared unavailable-or-ineligible artifact context with every available sequential artifact kind in canonical order.
func SelectSequentialListingArtifact(call native.Call, app types.CurrentAppRecordIndex, artifactKind types.ArtifactKind) (types.SequentialListingArtifactSelectionOutcome, error) {
	value, err := call.Invoke(selectSequentialListingArtifactFunction, []any{app, artifactKind})
	if err != nil {
		var zero types.SequentialListingArtifactSelectionOutcome
		return zero, err
	}
	return native.Output[types.SequentialListingArtifactSelectionOutcome](selectSequentialListingArtifactFunction, value)
}

var selectSequentialListingDomainFunction = native.Function{
	ID:        "operation.discovery_and_listing._select_sequential_listing_domain",
	Signature: "( artifact: SequentialArtifactRecordIndex, domain_namespace: DomainNamespace ) -> SequentialListingDomainSelectionOutcome",
}

// SelectSequentialListingDomain Selects one discovered sequential domain index or returns the shared unavailable-domain context with every available domain namespace in canonical order.
func SelectSequentialListingDomain(call native.Call, artifact types.SequentialArtifactRecordIndex, domainNamespace types.DomainNamespace) (types.SequentialListingDomainSelectionOutcome, error) {
	value, err := call.Invoke(selectSequentialListingDomainFunction, []any{artifact, domainNamespace})
	if err != nil {
		var zero types.SequentialListingDomainSelectionOutcome
		return zero, err
	}
	return native.Output[types.SequentialListingDomainSelectionOutcome](selectSequentialListingDomainFunction, value)
}

var validateSequentialRecordListingRequestFunction = native.Function{
	ID:        "operation.discovery_and_listing._validate_sequential_record_listing_request",
	Signature: "( request: SequentialRecordListingRequest ) -> SequentialRecordListingRequestValidationOutcome",
}

// ValidateSequentialRecordListingRequest Validates required selectors, projection values, limit bounds, and offset bounds in operation-defined order and applies every request default.
func ValidateSequentialRecordListingRequest(call native.Call, request types.SequentialRecordListingRequest) (types.SequentialRecordListingRequestValidationOutcome, error) {
	value, err := call.Invoke(validateSequentialRecordListingRequestFunction, []any{request})
	if err != nil {
		var zero types.SequentialRecordListingRequestValidationOutcome
		return zero, err
	}
	return native.Output[types.SequentialRecordListingRequestValidationOutcome](validateSequentialRecordListingRequestFunction, value)
}

var validateTreeChildListingRequestFunction = native.Function{
	ID:        "operation.discovery_and_listing._validate_tree_child_listing_request",
	Signature: "( request: TreeChildListingRequest, catalog: ArtifactModuleCatalog ) -> TreeChildListingRequestValidationOutcome",
}

// ValidateTreeChildListingRequest Validates one exact node reference, tree-kind eligibility, projection values, limit bounds, and offset bounds in operation-defined order and applies every request default.
func ValidateTreeChildListingRequest(call native.Call, request types.TreeChildListingRequest, catalog types.ArtifactModuleCatalog) (types.TreeChildListingRequestValidationOutcome, error) {
	value, err := call.Invoke(validateTreeChildListingRequestFunction, []any{request, catalog})
	if err != nil {
		var zero types.TreeChildListingRequestValidationOutcome
		return zero, err
	}
	return native.Output[types.TreeChildListingRequestValidationOutcome](validateTreeChildListingRequestFunction, value)
}

var validateTreeOverviewRequestFunction = native.Function{
	ID:        "operation.discovery_and_listing._validate_tree_overview_request",
	Signature: "( request: TreeOverviewRequest, catalog: ArtifactModuleCatalog ) -> TreeOverviewRequestValidationOutcome",
}

// ValidateTreeOverviewRequest Validates one exact node reference, tree-kind eligibility, depth bounds, and node-limit bounds in operation-defined order and applies every request default.
func ValidateTreeOverviewRequest(call native.Call, request types.TreeOverviewRequest, catalog types.ArtifactModuleCatalog) (types.TreeOverviewRequestValidationOutcome, error) {
	value, err := call.Invoke(validateTreeOverviewRequestFunction, []any{request, catalog})
	if err != nil {
		var zero types.TreeOverviewRequestValidationOutcome
		return zero, err
	}
	return native.Output[types.TreeOverviewRequestValidationOutcome](validateTreeOverviewRequestFunction, value)
}

var discoverRecordScopesFunction = native.Function{
	ID:        "operation.discovery_and_listing.discover_record_scopes",
	Signature: "( request: RecordScopeDiscoveryRequest ) -> RecordScopeDiscoveryOutcome",
}

// DiscoverRecordScopes Discovers configured app, artifact-kind, sequential-domain, or tree-root scopes according to one exact selector combination.
func DiscoverRecordScopes(call native.Call, request types.RecordScopeDiscoveryRequest) (types.RecordScopeDiscoveryOutcome, error) {
	value, err := call.Invoke(discoverRecordScopesFunction, []any{request})
	if err != nil {
		var zero types.RecordScopeDiscoveryOutcome
		return zero, err
	}
	return native.Output[types.RecordScopeDiscoveryOutcome](discoverRecordScopesFunction, value)
}

var inspectTreeFunction = native.Function{
	ID:        "operation.discovery_and_listing.inspect_tree",
	Signature: "( request: TreeOverviewRequest ) -> TreeOverviewOutcome",
}

// InspectTree Inspects one exact current tree subtree through bounded breadth-first selection and returns a nested structural overview.
func InspectTree(call native.Call, request types.TreeOverviewRequest) (types.TreeOverviewOutcome, error) {
	value, err := call.Invoke(inspectTreeFunction, []any{request})
	if err != nil {
		var zero types.TreeOverviewOutcome
		return zero, err
	}
	return native.Output[types.TreeOverviewOutcome](inspectTreeFunction, value)
}

var listSequentialRecordsFunction = native.Function{
	ID:        "operation.discovery_and_listing.list_sequential_records",
	Signature: "( request: SequentialRecordListingRequest ) -> SequentialRecordListingOutcome",
}

// ListSequentialRecords Lists one bounded ordered range of uniquely addressable current records within an exact sequential app, artifact-kind, and domain scope.
func ListSequentialRecords(call native.Call, request types.SequentialRecordListingRequest) (types.SequentialRecordListingOutcome, error) {
	value, err := call.Invoke(listSequentialRecordsFunction, []any{request})
	if err != nil {
		var zero types.SequentialRecordListingOutcome
		return zero, err
	}
	return native.Output[types.SequentialRecordListingOutcome](listSequentialRecordsFunction, value)
}

var listTreeChildrenFunction = native.Function{
	ID:        "operation.discovery_and_listing.list_tree_children",
	Signature: "( request: TreeChildListingRequest ) -> TreeChildListingOutcome",
}

// ListTreeChildren Lists one bounded range of direct current tree children for an exact canonical tree-node selector or reports the normal terminal-node result.
func ListTreeChildren(call native.Call, request types.TreeChildListingRequest) (types.TreeChildListingOutcome, error) {
	value, err := call.Invoke(listTreeChildrenFunction, []any{request})
	if err != nil {
		var zero types.TreeChildListingOutcome
		return zero, err
	}
	return native.Output[types.TreeChildListingOutcome](listTreeChildrenFunction, value)
}
