package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const generatedHeader = "// Code generated by PuppyDSL. DO NOT EDIT.\n\n"

func renderProgram(loaded program, outputDirectory string) error {
	if err := renderMetadata(loaded, outputDirectory); err != nil {
		return err
	}
	if err := renderTypes(loaded, outputDirectory); err != nil {
		return err
	}
	if err := renderFunctions(loaded, outputDirectory); err != nil {
		return err
	}
	if err := renderFunctionCatalog(loaded, outputDirectory); err != nil {
		return err
	}
	return renderManifests(loaded, outputDirectory)
}

func renderMetadata(loaded program, outputDirectory string) error {
	var source bytes.Buffer
	source.WriteString(generatedHeader)
	source.WriteString("package puppygen\n\n")
	source.WriteString("// SourceFingerprint identifies the exact sorted .puppy.yaml source set used for generation.\n")
	fmt.Fprintf(&source, "const SourceFingerprint = %s\n", strconv.Quote(loaded.SourceFingerprint))
	return writeFormatted(filepath.Join(outputDirectory, "metadata.gen.go"), source.Bytes())
}

func renderTypes(loaded program, outputDirectory string) error {
	directory := filepath.Join(outputDirectory, "types")
	var source bytes.Buffer
	source.WriteString(generatedHeader)
	source.WriteString("package types\n\n")

	membership := sortedUnionMembership(loaded.Types)
	for _, declaration := range loaded.Types {
		fmt.Fprintf(&source, "// %s %s\n", declaration.ID, sentence(declaration.Detail))
		switch declaration.Kind {
		case typeKindScalar:
			fmt.Fprintf(&source, "type %s %s\n\n", declaration.ID, primitiveGoTypes[declaration.Scalar])
		case typeKindEnum:
			fmt.Fprintf(&source, "type %s string\n\n", declaration.ID)
			source.WriteString("const (\n")
			for _, member := range declaration.Members {
				fmt.Fprintf(
					&source,
					"\t%s%s %s = %s\n",
					declaration.ID,
					goExportedName(member),
					declaration.ID,
					strconv.Quote(member),
				)
			}
			source.WriteString(")\n\n")
		case typeKindRecord:
			fmt.Fprintf(&source, "type %s struct {\n", declaration.ID)
			for _, field := range declaration.Fields {
				goType, err := renderGoType(field.Type, true)
				if err != nil {
					return fmt.Errorf("render type %s field %s: %w", declaration.ID, field.Name, err)
				}
				fmt.Fprintf(
					&source,
					"\t%s %s `json:%s yaml:%s`\n",
					goExportedName(field.Name),
					goType,
					strconv.Quote(field.Name),
					strconv.Quote(field.Name),
				)
			}
			source.WriteString("}\n\n")
		case typeKindUnion:
			fmt.Fprintf(&source, "type %s interface {\n", declaration.ID)
			fmt.Fprintf(&source, "\tis%s()\n", declaration.ID)
			source.WriteString("}\n\n")
		case typeKindOpaque:
			fmt.Fprintf(&source, "type %s struct {\n\tvalue any\n}\n\n", declaration.ID)
		}

		for _, unionID := range membership[declaration.ID] {
			fmt.Fprintf(&source, "func (%s) is%s() {}\n\n", declaration.ID, unionID)
		}
	}

	return writeFormatted(filepath.Join(directory, "types.gen.go"), source.Bytes())
}

func renderFunctionCatalog(loaded program, outputDirectory string) error {
	declarations := append([]functionDeclaration(nil), loaded.Functions...)
	sort.Slice(declarations, func(left, right int) bool {
		return declarations[left].ID < declarations[right].ID
	})

	packagePaths := map[string]struct{}{}
	for _, declaration := range declarations {
		if relativePath := filepath.ToSlash(declaration.packageRelativePath()); relativePath != "" {
			packagePaths[relativePath] = struct{}{}
		}
	}

	sortedPaths := make([]string, 0, len(packagePaths))
	for path := range packagePaths {
		sortedPaths = append(sortedPaths, path)
	}
	sort.Strings(sortedPaths)

	aliases := make(map[string]string, len(sortedPaths))
	var source bytes.Buffer
	source.WriteString(generatedHeader)
	source.WriteString("package puppygen\n\n")
	if len(sortedPaths) > 0 {
		source.WriteString("import (\n")
		for index, relativePath := range sortedPaths {
			alias := fmt.Sprintf("functionpkg%d", index)
			aliases[relativePath] = alias
			importPath := loaded.OutputImportPath + "/" + relativePath
			fmt.Fprintf(&source, "\t%s %s\n", alias, strconv.Quote(importPath))
		}
		source.WriteString(")\n\n")
	}

	source.WriteString("// Functions indexes every declared FunctionID to its generated typed caller facade.\n")
	source.WriteString("var Functions = map[string]any{\n")
	for _, declaration := range declarations {
		facade := declaration.GoName
		if relativePath := filepath.ToSlash(declaration.packageRelativePath()); relativePath != "" {
			facade = aliases[relativePath] + "." + declaration.GoName
		}
		fmt.Fprintf(&source, "\t%s: %s,\n", strconv.Quote(declaration.ID), facade)
	}
	source.WriteString("}\n")

	return writeFormatted(filepath.Join(outputDirectory, "function_catalog.gen.go"), source.Bytes())
}

func renderFunctions(loaded program, outputDirectory string) error {
	packages := map[string][]functionDeclaration{}
	for _, declaration := range loaded.Functions {
		path := declaration.packageRelativePath()
		packages[path] = append(packages[path], declaration)
	}
	paths := make([]string, 0, len(packages))
	for path := range packages {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, relativePath := range paths {
		declarations := packages[relativePath]
		sort.Slice(declarations, func(left, right int) bool {
			return declarations[left].ID < declarations[right].ID
		})
		if err := renderFunctionPackage(loaded, outputDirectory, relativePath, declarations); err != nil {
			return err
		}
	}
	return nil
}

func renderFunctionPackage(
	loaded program,
	outputDirectory string,
	relativePath string,
	declarations []functionDeclaration,
) error {
	packageName := "puppygen"
	if relativePath != "" {
		parts := strings.Split(filepath.ToSlash(relativePath), "/")
		packageName = parts[len(parts)-1]
	}

	usesTypes := false
	for _, declaration := range declarations {
		if signatureUsesGeneratedType(declaration.Signature) {
			usesTypes = true
			break
		}
	}

	var source bytes.Buffer
	source.WriteString(generatedHeader)
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	source.WriteString("import (\n")
	fmt.Fprintf(&source, "\tnative %s\n", strconv.Quote(loaded.NativeImportPath))
	if usesTypes {
		fmt.Fprintf(&source, "\ttypes %s\n", strconv.Quote(loaded.OutputImportPath+"/types"))
	}
	source.WriteString(")\n\n")

	for _, declaration := range declarations {
		if err := renderFunction(&source, declaration); err != nil {
			return err
		}
	}

	directory := outputDirectory
	if relativePath != "" {
		directory = filepath.Join(outputDirectory, relativePath)
	}
	return writeFormatted(filepath.Join(directory, "functions.gen.go"), source.Bytes())
}

func renderFunction(source *bytes.Buffer, declaration functionDeclaration) error {
	descriptorName := goLocalName(declaration.GoName) + "Function"
	canonicalSignature := strings.Join(strings.Fields(declaration.SignatureSource), " ")
	fmt.Fprintf(source, "var %s = native.Function{\n", descriptorName)
	fmt.Fprintf(source, "\tID: %s,\n", strconv.Quote(declaration.ID))
	fmt.Fprintf(source, "\tSignature: %s,\n", strconv.Quote(canonicalSignature))
	source.WriteString("}\n\n")

	parameters, arguments, err := renderFunctionParameters(declaration.Signature.Inputs)
	if err != nil {
		return fmt.Errorf("render function %s parameters: %w", declaration.ID, err)
	}
	outputType, err := renderGoType(declaration.Signature.Output, false)
	if err != nil {
		return fmt.Errorf("render function %s output: %w", declaration.ID, err)
	}
	returnsControl := declaration.Signature.Output.Name == "void" || declaration.Signature.Output.Name == "never"

	fmt.Fprintf(source, "// %s %s\n", declaration.GoName, sentence(declaration.Detail))
	fmt.Fprintf(source, "func %s(call native.Call%s)", declaration.GoName, parameters)
	if returnsControl {
		source.WriteString(" error {\n")
		fmt.Fprintf(source, "\t_, err := call.Invoke(%s, %s)\n", descriptorName, arguments)
		source.WriteString("\treturn err\n")
	} else {
		fmt.Fprintf(source, " (%s, error) {\n", outputType)
		fmt.Fprintf(source, "\tvalue, err := call.Invoke(%s, %s)\n", descriptorName, arguments)
		source.WriteString("\tif err != nil {\n")
		fmt.Fprintf(source, "\t\tvar zero %s\n", outputType)
		source.WriteString("\t\treturn zero, err\n\t}\n")
		fmt.Fprintf(source, "\treturn native.Output[%s](%s, value)\n", outputType, descriptorName)
	}
	source.WriteString("}\n\n")

	if declaration.Implementation != implementationNative {
		return nil
	}

	implementationType := declaration.GoName + "Implementation"
	fmt.Fprintf(source, "// %s is the concrete Go signature accepted by Bind%s.\n", implementationType, declaration.GoName)
	fmt.Fprintf(source, "type %s func(call native.Call%s)", implementationType, parameters)
	if returnsControl {
		source.WriteString(" error\n\n")
	} else {
		fmt.Fprintf(source, " (%s, error)\n\n", outputType)
	}

	fmt.Fprintf(source, "// Bind%s binds a Go implementation to PuppyDSL function %s.\n", declaration.GoName, declaration.ID)
	fmt.Fprintf(source, "func Bind%s(implementation %s) native.Binding {\n", declaration.GoName, implementationType)
	fmt.Fprintf(source, "\tif implementation == nil {\n")
	fmt.Fprintf(
		source,
		"\t\treturn native.NewBinding(%s, %s, nil)\n",
		descriptorName,
		strconv.Quote(declaration.NativeBindingID),
	)
	fmt.Fprintf(source, "\t}\n")
	fmt.Fprintf(source, "\treturn native.NewBinding(\n")
	fmt.Fprintf(source, "\t\t%s,\n", descriptorName)
	fmt.Fprintf(source, "\t\t%s,\n", strconv.Quote(declaration.NativeBindingID))
	fmt.Fprintf(source, "\t\tfunc(call native.Call, arguments []any) (any, error) {\n")
	fmt.Fprintf(source, "\t\t\tif len(arguments) != %d {\n", len(declaration.Signature.Inputs))
	fmt.Fprintf(
		source,
		"\t\t\t\treturn nil, native.ArgumentCountError(%s, %d, len(arguments))\n",
		descriptorName,
		len(declaration.Signature.Inputs),
	)
	fmt.Fprintf(source, "\t\t\t}\n")

	invocationArguments := make([]string, 0, len(declaration.Signature.Inputs)+1)
	invocationArguments = append(invocationArguments, "call")
	for index, input := range declaration.Signature.Inputs {
		inputType, inputErr := renderGoType(input.Type, false)
		if inputErr != nil {
			return fmt.Errorf("render function %s native input %s: %w", declaration.ID, input.Name, inputErr)
		}
		inputName := fmt.Sprintf("input%d", index)
		fmt.Fprintf(
			source,
			"\t\t\t%s, err := native.Input[%s](%s, arguments, %d, %s)\n",
			inputName,
			inputType,
			descriptorName,
			index,
			strconv.Quote(input.Name),
		)
		fmt.Fprintf(source, "\t\t\tif err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n")
		invocationArguments = append(invocationArguments, inputName)
	}

	invocation := strings.Join(invocationArguments, ", ")
	if returnsControl {
		fmt.Fprintf(source, "\t\t\tif err := implementation(%s); err != nil {\n", invocation)
		fmt.Fprintf(source, "\t\t\t\treturn nil, err\n\t\t\t}\n")
		fmt.Fprintf(source, "\t\t\treturn nil, nil\n")
	} else {
		fmt.Fprintf(source, "\t\t\tresult, err := implementation(%s)\n", invocation)
		fmt.Fprintf(source, "\t\t\tif err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n")
		fmt.Fprintf(source, "\t\t\treturn result, nil\n")
	}
	fmt.Fprintf(source, "\t\t},\n")
	fmt.Fprintf(source, "\t)\n")
	source.WriteString("}\n\n")
	return nil
}

func renderFunctionParameters(inputs []functionInput) (string, string, error) {
	if len(inputs) == 0 {
		return "", "nil", nil
	}
	var parameters strings.Builder
	var arguments strings.Builder
	arguments.WriteString("[]any{")
	for index, input := range inputs {
		goType, err := renderGoType(input.Type, false)
		if err != nil {
			return "", "", err
		}
		name := goLocalName(input.Name)
		fmt.Fprintf(&parameters, ", %s %s", name, goType)
		if index > 0 {
			arguments.WriteString(", ")
		}
		arguments.WriteString(name)
	}
	arguments.WriteString("}")
	return parameters.String(), arguments.String(), nil
}

func renderGoType(expression typeExpression, inTypesPackage bool) (string, error) {
	if primitive, exists := primitiveGoTypes[expression.Name]; exists {
		return primitive, nil
	}
	switch expression.Name {
	case "void", "never":
		return "", nil
	case "list":
		argument, err := renderGoType(expression.Arguments[0], inTypesPackage)
		if err != nil {
			return "", err
		}
		return "[]" + argument, nil
	case "optional":
		argument, err := renderGoType(expression.Arguments[0], inTypesPackage)
		if err != nil {
			return "", err
		}
		return "*" + argument, nil
	case "dict":
		key, err := renderGoType(expression.Arguments[0], inTypesPackage)
		if err != nil {
			return "", err
		}
		value, err := renderGoType(expression.Arguments[1], inTypesPackage)
		if err != nil {
			return "", err
		}
		return "map[" + key + "]" + value, nil
	default:
		if inTypesPackage {
			return expression.Name, nil
		}
		return "types." + expression.Name, nil
	}
}

func signatureUsesGeneratedType(signature functionSignature) bool {
	for _, input := range signature.Inputs {
		if expressionUsesGeneratedType(input.Type) {
			return true
		}
	}
	return expressionUsesGeneratedType(signature.Output)
}

func expressionUsesGeneratedType(expression typeExpression) bool {
	if _, primitive := primitiveGoTypes[expression.Name]; primitive {
		return false
	}
	if expression.Name == "void" || expression.Name == "never" {
		return false
	}
	if expression.Name != "list" && expression.Name != "optional" && expression.Name != "dict" {
		return true
	}
	for _, argument := range expression.Arguments {
		if expressionUsesGeneratedType(argument) {
			return true
		}
	}
	return false
}

func sentence(value string) string {
	value = strings.TrimSpace(value)
	if value == "" || strings.HasSuffix(value, ".") {
		return value
	}
	return value + "."
}

func writeFormatted(path string, source []byte) error {
	formatted, err := format.Source(source)
	if err != nil {
		return fmt.Errorf("format generated %s: %w\n%s", path, err, source)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create generated directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated %s: %w", path, err)
	}
	return nil
}
