// Code generated by PuppyDSL. DO NOT EDIT.

package puppygen

import (
	native "github.com/hiroshiasayadev-prog/brewprint/puppydsl/src/native"
)

var mainFunction = native.Function{
	ID:        "main",
	Signature: "() -> void",
}

// Main Opens the process-lifetime runtime contexts and serves the configured public MCP tools.
func Main(call native.Call) error {
	_, err := call.Invoke(mainFunction, nil)
	return err
}
