// Code generated by PuppyDSL. DO NOT EDIT.

package puppygen

// SourceFingerprint identifies the exact sorted .puppy.yaml source set used for generation.
const SourceFingerprint = "5cf4e59a6bd0a1fd5e523de0db0543f7f56e05d4131ff1a116f7e35c94d9e923"
